### ISSUE TITLE
Feature request: Set current country programatically

### ISSUE THREAD

**Issue by zofrex** [Bluefieldscom/intl-tel-input#1]
e.g: $('#telephone').setDefaultCountry('GB');

This would change which country the input is set to, intended for use only before the user has entered anything (so if they've selected a country themselves, I don't think it would make sense to change that)

This would be useful when multiple inputs on a form need to vary based on the user's country - for example if you had an address input and a telephone input, you might want to adapt both visually based on their country, but only ask them for their country once. This way if they select their country in some previous form step, when we show them an empty telephone input, we can have their country already selected.

(It could also be used for guessing what country to display based on e.g. geolocation)

**Comment by lbraun** [comment]
For those of you coming to this in 2019, you will want to do something more like:
```
var input = document.querySelector('#telephone');
var instance = window.intlTelInputGlobals.getInstance(input);
instance.setCountry('GB');
```
