### ISSUE TITLE
Using in Modal Dialog

### ISSUE THREAD

**Issue by lionsgatecreative** [Bluefieldscom/intl-tel-input#100]
Great plugin! I'm trying to also use it in a modal dialog, but an issue. One does see the country dropdown which works. However, the number is not formatted as it is entered: no space after country code, and no hyphens. Number input is formatted when used outside modal dialog. I even set autoFormat to true in the modal, but no luck. The plugin JS is in the modal dialog (called as an external page).

**Comment by mariyappan88** [comment]
hi @jackocnr , Can you please mention how do you resolve this issue? How to use loadUtils method?
