### ISSUE TITLE
Cannot the set PhoneNumber and Country Code DropDown as ReadOnly

### ISSUE THREAD

**Issue by ManiMaranVasan** [Bluefieldscom/intl-tel-input#108]
Hi,
    I can't set the TextBox as Readonly field

My code:
<input id="mobile-number" type="tel"  readonly>

But still i can edit number and choose the country from dropdown
![issue_on_phonenumberdropdown](https://cloud.githubusercontent.com/assets/9625784/5006450/a431939c-6a68-11e4-836e-ddf5310948f6.png)

Kindly help me to solve this

**Comment by jackocnr** [comment]
Ok the plugin now supports readonly inputs as of v3.8.0.
