### ISSUE TITLE
Invalid country codes are "accepted"

### ISSUE THREAD

**Issue by flyrev** [Bluefieldscom/intl-tel-input#109]
If you enter a number with an invalid country code (+0 or +28, say), the old flag remains. One can then enter as many digits as desired.

How to reproduce: click in the field, enter +000000
or for that matter: enter +28 ...

**Comment by jackocnr** [comment]
Slight update on this issue: I'm now moving towards enabling nationalMode by default as I think it solves so many of these problems and is a MUCH better experience for the user anyway (it means they just get to enter their national number and not have to think about country codes). I wanted to ask: have you considered using nationalMode?

**Comment by jackocnr** [comment]
I've added an empty state for the flag when you dial an invalid dial code, but I'm moving away from preventing the user from doing anything. Instead I think you should just do a full validation check on blur or submit.
