### ISSUE TITLE
Samoa numbers are invalid

### ISSUE THREAD

**Issue by aleksandrpanteleymonov** [Bluefieldscom/intl-tel-input#110]
Due to a bug in libphonelibrary https://code.google.com/p/libphonenumber/issues/detail?id=555, all Samoa phone numbers are invalid now.

Also, it won't be fixed fast, so we need to find another way to validate numbers as you type.
https://code.google.com/p/libphonenumber/issues/detail?id=555#c3

**Comment by jackocnr** [comment]
Added `preventInvalidNumbers` option in v3.8.0 which defaults to false.

**Comment by garybond** [comment]
Does the issue with Samoa (and possibly others) also manifest itself when calling isValidNumber?
ie, if you set preventInvalidNumbers to true but also use isValidNumber before submission, will the Samoa number validation still be an issue?

**Comment by jackocnr** [comment]
You must leave `preventInvalidNumbers` set to false if you want to enter Samoa numbers (until they fix that bug) - that was the point of separating out that option.

As for `isValidNumber` - I think this should work ok for Samoa numbers as I believe the [libphonenumber bug](http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html) is specific to the AsYouTypeFormatter, not the validation part, but please double check to make sure.
