### ISSUE TITLE
Cursor in wrong position when entering a digit at the start of the input

### ISSUE THREAD

**Issue by prollinson** [Bluefieldscom/intl-tel-input#111]
This issue occurs when a (US formatted) number consists of 7 digits and a user attempts to enter a digit at the start of the input. The cursor jumps back to the beginning of the string after entering the digit.

This obviously causes problems when quickly re-entering a number, as the number ends up incorrect.

Please can you fix this ASAP.

Thanks! :)

**Comment by jackocnr** [comment]
There was also an issue with backspace/deletes. Both issues fixed in v3.8.2.
