### ISSUE TITLE
Auto formatting and validation not working in Rails text_field_tag

### ISSUE THREAD

**Issue by cmacalin** [Bluefieldscom/intl-tel-input#113]
I am using intl-tel-input in a form text_field_tag, inside a modal, with Ruby on Rails 4 (setup shown below). However, when I type something into the phone number field, I can type letters and the numbers aren't automatically formatted with dashes. 

Javascript and CSS file calls: 

``` html
<%= stylesheet_link_tag :intlTelInput, "bootstrap-datetimepicker.min.css", "my-styles.css" %>
<%= javascript_include_tag "jquery.modalEffects.js", :moment, "bootstrap-datetimepicker.min.js", "jquery-ui.js", "intlTelInput.min.js", "my-javascript.js"  %>
```

HTML in file: 

``` rails
<%= form_tag([:webapp, Plan.new], :class => "phone-create-form", autocomplete:"off") do %>
    <div class="form-group col-md-12">
        <%= text_field_tag(:dialin_phone_number, nil, placeholder:"Phone Number", :class => "form-control", :id => "phone_num_input", required:true) %>
    </div>
<% end %>
```

jQuery Call:

``` javascript
  $("#phone_num_input").intlTelInput({
    utilsScript: "/assets/utils.js"
  });
```

Please let me know if you need any additional information about the setup. This was the first thing I added to the modal form and it worked initially. I noticed the formatting and validation stopped working once I started adding in ajax requests and other plugins.

**Comment by jatasya** [comment]
Thank you,

                The loadUtils funtion worked for me when lazy loading.

                   $("#phone").intlTelInput({
                            initialCountry: "auto",
                            getNumberType:"MOBILE",
                            geoIpLookup: function(callback) {
                            $.get('http://ipinfo.io', function() {}, "jsonp").always(function(resp) {
                            var countryCode = (resp && resp.country) ? resp.country : "";
                            callback(countryCode);
                    });
                },
                utilsScript: $.fn.intlTelInput.loadUtils("js/utils.js")
                });
