### ISSUE TITLE
Wrong display of rtl country names

### ISSUE THREAD

**Issue by opanteleimonov** [Bluefieldscom/intl-tel-input#116]
Hi!
Currently, rtl names (arabic) diplays wrong like this:
http://i.imgur.com/t1WwbW4.png
It could be fixed with <bdi> tag, for example like this:

``` html
<span class="country-name">Pakistan (<bdi>پاکستان</bdi>)</span>
```

As a result it will be diplayed correctly:
http://i.imgur.com/1rwoQSV.png

**Comment by khanhvuNOIS** [comment]
https://www.shanab.moda/ar/login
please take a look on my website sir. I just use your plugin but there's issue with display right to left. Can you help me to resolve it. Also i have problem when make flag bigger. My client need bigger so that old man can use website
