### ISSUE TITLE
Autocomplete circumvents the plugins ability to set a country code

### ISSUE THREAD

**Issue by taylorcode** [Bluefieldscom/intl-tel-input#117]
When the user selects an autocomplete value, the number formatting feature is circumvented.

Because of this, a country code in the number is ignored, and it defaults to "1" in the plugins instance "selectedCountryData.dialCode".

 On a number selected from autocomplete without a country code, selectedCountryData.dialCode is "1".

**Comment by jackocnr** [comment]
This was released in v3.8.0.
