### ISSUE TITLE
Not allowed phone codes

### ISSUE THREAD

**Issue by lutaev** [Bluefieldscom/intl-tel-input#120]
Here http://en.wikipedia.org/wiki/List_of_country_calling_codes you can find list of country calling codes. Some codes do not belong to one of the countries, but in plugin it is not taken.

**Comment by jackocnr** [comment]
Slight update on this issue: I'm now moving towards enabling nationalMode by default as I think it solves so many of these problems and is a MUCH better experience for the user anyway (it means they just get to enter their national number and not have to think about country codes). I wanted to ask: have you considered using nationalMode?

**Comment by lutaev** [comment]
I don't understand what means phrase "not have to think about country codes". Like what numbers with nationalMode swithed on look?

**Comment by jackocnr** [comment]
So for an American number "+1 702 123 4567" you would just type "702 123 4567". See the example here: http://jackocnr.com/lib/intl-tel-input/examples/gen/national-mode.html

Try typing a valid national number on the example page, and you will see how the code uses `getCleanNumber` to get the full international number.

**Comment by lutaev** [comment]
Sorry, but nationalMode is not the thing I need. I need a method which can validate number depending of start digits.

**Comment by jackocnr** [comment]
I've added an empty state for the flag when you dial an invalid dial code, but I'm moving away from preventing the user from doing anything. Instead I think you should just do a full validation check on blur or submit.
