### ISSUE TITLE
Can I do not cut phone numbers?

### ISSUE THREAD

**Issue by lutaev** [Bluefieldscom/intl-tel-input#121]
Hello.
I have a proposal: may be we should allow phone numbers exceed the limits of standarts and switch of formatting in this case like this.

__Initialization:__
```javascript
$('#someInput').intlTelInput({
    nationalMode: false,
    smartFormat: true,
    autoHideDialCode: false,
});
```
and __updateVal()__ method:
```javascript
function(val, addSuffix) {
    var formatted;
    if (this.options.autoFormat && window.intlTelInputUtils) {
        formatted = intlTelInputUtils.formatNumber(val, this.selectedCountryData.iso2, addSuffix);

        var valNotFormatted = val.replace(/[\-\+\s]/g, '');
        if(addSuffix !== undefined && this.options.smartFormat && formatted.replace(/[\-\+\s]/g, '') != valNotFormatted){
            formatted = '+' + valNotFormatted;
        }

        // ensure we dont go over maxlength. we must do this here to truncate any formatting suffix, and also handle paste events
        var max = this.telInput.attr("maxlength");
        if (max && formatted.length > max) {
            formatted = formatted.substr(0, max);
        }
    }
    else {
        // no autoFormat, so just insert the original value
        formatted = val;
    }
    this.telInput.val(formatted);
}
```
 What do you think about this?

**Comment by jackocnr** [comment]
Added `preventInvalidNumbers` option in v3.8.0 which defaults to false.

**Comment by lutaev** [comment]
Hi!
I'm working in branch "denyWrongCodes" and I've a problem.
Your commit https://github.com/Bluefieldscom/intl-tel-input/commit/8f53f8c8caf152a7233ccbe0b77c09763fc44052 destroyed my functionality , because your function "formatNumber" make my parameter "smartFormat" useless.

May be I'm not right, because, in previous comment you told that I should use "preventInvalidNumbers" option for this functionality. But in current code we have no this option! How can it be possible?

**Comment by jackocnr** [comment]
Hi there. If you look through the [release notes](https://github.com/Bluefieldscom/intl-tel-input/releases) you can see that I removed `preventInvalidNumbers` in v5.0.0 back in January (remember: major release numbers often mean breaking changes), giving the reason: "Removed preventInvalidNumbers as was wrongly using libphonenumber's AsYouTypeFormatter, which was broken and they explicitly said shouldn't be used for that".

The current functionality though is still what you described before: the plugin adds formatting for valid numbers, but if they type too many digits, it removes all formatting.
