### ISSUE TITLE
ISO3 Code usage

### ISSUE THREAD

**Issue by michaelrimbach** [Bluefieldscom/intl-tel-input#127]
Hello,

do you have any reasons why you dont use iso3 codes instead of iso2? 

It would be a great feature if we could use both. (Specially we need iso3)

Kind regards,
Michael

**Comment by jackocnr** [comment]
Closed due to lack of activity.

**Comment by kaydwithers** [comment]
I would also like to suggest using iso3. It is handy for use in Airports.
