### ISSUE TITLE
Auto lock country code after selection?

### ISSUE THREAD

**Issue by zocheyado** [Bluefieldscom/intl-tel-input#128]
How would it be possible to prevent manually editing the country code? I am hoping that a user can ONLY enter country code by selecting a flag. Or, hide the country code from the input and connect the two later. People are deleting the country code and failing to receive texts.

**Comment by jackocnr** [comment]
You should use the built-in public method isValidNumber to check the number is valid before submitting the form. Example here: http://jackocnr.com/lib/intl-tel-input/examples/gen/is-valid-number.html

 Does that solve your problem?

**Comment by zocheyado** [comment]
Not exactly, so even in that example my issue still persists. We did a blind test on 10 people on our site and 3 of them erased the country code +1 (all american testers) which left +, then they typed their area code but as they typed as you can imagine the country code changed. So three separate people tried to type in their number after erasing the country code because quote "I don't know what that is" I know it seems ridiculous but I am trying to make it so that ONLY the drop down can edit the country code. Any ideas?

**Comment by jackocnr** [comment]
Why don't you use nationalMode so users are expected to enter just their
national number?

**Comment by zocheyado** [comment]
Because of the issue above, americans will not do this as they never have to. Most of our users are US (80%) and if 3 out of 10 did not know what a country code was thats too many people to request a country code. I might just fork and try and add it.

**Comment by jackocnr** [comment]
The point of nationalMode is that users don't have to enter the country
code...

**Comment by zocheyado** [comment]
Oh I assumed it was the opposite based on your wording, after seeing the example I think that will work for what I want! I apologize for the issues.
