### ISSUE TITLE
Minified version ≠ Unminified version

### ISSUE THREAD

**Issue by erem-ifg** [Bluefieldscom/intl-tel-input#130]
https://github.com/Bluefieldscom/intl-tel-input/tree/master/build/js

It seems like the current unminified version does not support ipinfo SSL

**Comment by jackocnr** [comment]
It looks like it does to me: https://github.com/Bluefieldscom/intl-tel-input/blob/master/build/js/intlTelInput.js#L79

Here's the pull request that I merged to add support for HTTPS: https://github.com/Bluefieldscom/intl-tel-input/pull/97/files

You can see the URL change from "http://ipinfo.io" to "//ipinfo.io" which means it will use HTTPS if the page is using HTTPS.

What error are you seeing?

**Comment by erem-ifg** [comment]
Sorry I was not very explicit.

The error I got was from ipinfo:
`GET https://ipinfo.io/?callback=jQuery11020442816355265677_1421055651263&_=1421055651264`

`SSL access is restricted to paid plans. See http://ipinfo.io/pricing for more details, or contact us via http://ipinfo.io/contact`

The token is not passed to the request parameters.
It works with the unminified version though.
I thought the error was because the version of the unminified version (3.8.4) is different from the unminified version (3.8.3).

**Comment by jackocnr** [comment]
You are right, `ipinfoToken` and `preventInvalidNumbers` options are not working in the minified build file. This is due to a problem in the build process which I will fix post haste! Thanks for letting me know!

**Comment by jackocnr** [comment]
Fixed in v3.8.6. Thanks again.
