### ISSUE TITLE
Missing lib/ subdirectories referenced in tests

### ISSUE THREAD

**Issue by idpaterson** [Bluefieldscom/intl-tel-input#131]
After cloning the repository I installed npm and bower dependencies. However, the tests depend on what seem to be copies of the bower modules located within a lib directory. The files are .gitignored and not tracked, so all tests fail.

First I tried changing the bower directory to lib thinking that perhaps the following `.bowerrc` file was not checked in:
```json
{
    "directory": "lib"
}
```

After doing so and reinstalling bower dependencies, the paths did not quite match. In grunt/jasmine.js the dependency paths were listed as
```js
vendor: [
  'lib/jquery/jquery.js',
  'lib/jasmine-jquery/jasmine-jquery.js'
],
```
However, the bower module paths (after installing bower modules in lib/) were
```js
vendor: [
  'lib/jquery/dist/jquery.js',
  'lib/jasmine-jquery/lib/jasmine-jquery.js'
],
```

I then realized that there is a lib/libphonenumber in the repository where it has been modified for your purposes, so using lib/ for the bower directory was not the right solution as it would overwrite your customizations.

Since the lib/ subdirectories for jquery are .gitignored, do you just use symlinks to bower_modules/? I intended to submit a pull request for this since it is an obstacle to contributing to the project, but I couldn't decipher which was the correct solution:
* Change references from lib/ to bower_modules/ and update paths
* Add and commit symlinks in lib/ to bower_modules/ (may cause issues on other filesystems) 
* Specify a more strict version requirement for jquery in bower.json's `devDependencies` so that the paths are reliable for testing without affecting compatibility with older jQuery versions for production use

**Comment by jackocnr** [comment]
Hey sorry for the confusion, I'm currently managing the bower stuff through grunt, so you have to run `grunt bower` to install the bower dependencies in the right place.

I just cloned the project, ran `npm install` then `grunt bower` then `grunt build` and the tests passed. I've updated the readme accordingly. Does that solve your problem?

BTW in the future I think I'll probably remove bower and just do everything through npm for simplicity.

**Comment by idpaterson** [comment]
Thanks, I was looking at grunt-bower rather than grunt-bower-tasks in trying to figure out what the bower task was for, didn't bother to check package.json or run it d'oh! Makes sense now why everything works fine on travis.
