### ISSUE TITLE
Area code 226 should be in Canada, not the US

### ISSUE THREAD

**Issue by cpbillfinlay** [Bluefieldscom/intl-tel-input#133]
The area code 226 is a Canadian area code, but intl-tel-input thinks it's a US area code. Wikipedia can confirm this is a Canadian area code: http://en.wikipedia.org/wiki/Area_codes_519_and_226

Steps to reproduce:
- Navigate to http://jackocnr.com/intl-tel-input.html
- Select Canada from the country dropdown.
- Type "226" into the text field.

The country dropdown will change to the United States.

In contrast, libphonenumber demos seem to yield the correct results. E.g.:
- Navigate to http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
- Enter the phone number "2265551234".
- Enter the default country "US".
- Click Submit.

The validation results show "Phone Number region: CA"

**Comment by jackocnr** [comment]
Thanks for reporting this. Fixed in v3.8.7.
