### ISSUE TITLE
How to make this library run on https?

### ISSUE THREAD

**Issue by sachin87** [Bluefieldscom/intl-tel-input#134]
I am getting this error in my firebug console:-

 Mixed Content: The page at 'https://secure.comeasure.in/payments/?utf8=%E2%9C%93&nights=1&arrival_date=…B0%5D=TWIN%3ATwin&roomstr=Superior+Single+x+1%3Cbr%2F%3E&totalprice=3284.1' was loaded over HTTPS, but requested an insecure script 'http://ipinfo.io/?callback=jQuery111108757403229828924_1421254476773&_=1421254476774'. This request has been blocked; the content must be served over HTTPS.

As we can see it is trying to  find default country while loading but http requests and contents are being blocked on my page.
I think it will work if i somehow set:
ipinfoURL = "https://ipinfo.io"

But not sure how to do that.

**Comment by jackocnr** [comment]
What version of the plugin are you using? The latest version should use the same HTTP/HTTPS as the page.

**Comment by sachin87** [comment]
ntl-tel-input 3.6.0

**Comment by jackocnr** [comment]
Yer if you update to the latest version then it will work.
