### ISSUE TITLE
Method to get only phone number without country code?

### ISSUE THREAD

**Issue by rderharo** [Bluefieldscom/intl-tel-input#135]
This plugin is great, but the only thing I find that is missing is being able to easily just grab the phone number without the country code (in my case I want to store the values separately).

I know that the `getSelectedCountryData` method can give me the country code so I can use regex to find out the rest, but it would be a lot easier if the plugin exposed a method to do that.

**Comment by jackocnr** [comment]
Have you considered using the nationalMode option? That way users would only be entering national numbers (no country code).

**Comment by rderharo** [comment]
Yes, for display purposes it works great, but on submit I need to pass the country code and actual phone number as separate values. 

Right now all I can find is `getCleanNumber` but that will return me the full number with country code included.

**Comment by jackocnr** [comment]
But with nationalMode enabled, the phone number bit is just the input value... so you can get it with `$("input").val()`. But I suppose it could have formatting chars.

I'm thinking about changing `getCleanNumber` to just `getNumber` and have it take an optional argument for national/international etc. Would that solve your problem?

**Comment by rderharo** [comment]
Oh, I see, thanks! Yes, I can just grab the input value to get the phone number and use regex to strip the formatting.

It's not that I don't want the country code, it's just that I want to separate the values so I can store them separately. So actually having a `getNumber` and a `getDialCode` would solve my problem, but I can also just grab the input like you suggested above and then do `getSelectedCountryData` to get the dial code.

**Comment by jackocnr** [comment]
Cool - I'm glad you have a solution. So I'm interested: what do you think of the nationalMode option? I was thinking of defaulting it to enabled as I think it's a better experience for the user. Any thoughts?

**Comment by rderharo** [comment]
I was debating between having nationalMode on or not, but in the end I'm going to leave it on. 

Having it off makes keyboard usage a bit faster since you can type the country code if you know it, but it's more likely that the user would prefer to select the country from the drop down and simply enter their phone number after (users probably don't care about country codes).

So yes, from a user experience point of view maybe it makes sense to have nationalMode on by default.

**Comment by jackocnr** [comment]
Also in nationalMode they can still type the full number (with country code) if they want, and it will update the flag... Best of both worlds!

Cool. I'm going to do that in v4.0. Thanks.

**Comment by jackocnr** [comment]
I'm going to leave this issue open until I have added that `getNumber` method, and updated nationalMode to default to true.

**Comment by jackocnr** [comment]
Added in v4.0.0.

**Comment by rderharo** [comment]
Awesome, thanks! And thanks for the speedy response, too.

**Comment by rahulthackkar** [comment]
Hi @jackocnr 
Sorry to ask you again this, but can you please tell me how can I get national number from user input?

user input value : +919974812345 
auto selected country is : India

Now I need to get "91" and "9974812345" as separate values, can you please guide me with this?

**Comment by sujithkris** [comment]
> Hi @jackocnr
> Sorry to ask you again this, but can you please tell me how can I get national number from user input?
> 
> user input value : +919974812345
> auto selected country is : India
> 
> Now I need to get "91" and "9974812345" as separate values, can you please guide me with this?

```
var fullnumber = $('#phone-number-field').val();
var countryCode = $('#phone-number-field').intlTelInput("getDialCode");
```
Replace _countryCode_  in _fullnumber_ with emptry string to get 10 digit number

**Comment by rahulthackkar** [comment]
**Big Thanks** @sujithkris for your answer.

I already have this logic with core javascript, my question was , is there any method in this library to get number without country code?

I tried with formatNumber utility with NATIONAL option like

`var nationalNumber = intlTelInputUtils.formatNumber('+919974812345', itiInstance.getSelectedCountryData().dialCode, intlTelInputUtils.numberFormat.NATIONAL);`

But it returns "09974812345" , I dont want 0, expected output is only number without country code that is "9974812345".

Your efforts are appricialble.
Thanks

**Comment by rahulthackkar** [comment]
as user can input both "+919974812345" and "919974812345" , both are valid numbers for india , but I need to replace +91 with empty string in first case and "91" with empty string in other to get national number.
any suggestions?

**Comment by jackocnr** [comment]
@rahulthackkar the plugin can only format to national format, as you have seen. If you want the international format minus the dial code, you'll have to do that yourself with JavaScript - it's just simple string manipulation. If you're not sure how to do that I suggest you ask on StackOverflow.

**Comment by rahulthackkar** [comment]
thanks @jackocnr,

I know how to do that.

**Comment by rahulthackkar** [comment]
One more question @jackocnr 
 User input is 919974812345

How can I decide that I need to remove 91?
If I decide it from selected country data dialCode then it is fine for above number, but what if user input is 
9174612345 (valid number, without country code specified (no filter needed)) for india, here it is difficult to decide that weather user has entered mobile number with country code or without country code.

Can you suggest me solution for this?

**Comment by jackocnr** [comment]
If you use `getNumber` you will get the full number including the dial code, so safe to remove the dial code from that.

**Comment by rahulthackkar** [comment]
Ohh yes, perfectly works fine with that.

Thanks a lot @jackocnr

**Comment by ayaseensd** [comment]
**I think using JS will gives you phone number without +91**

```
var input = document.querySelector("#phone")
    var iti = window.intlTelInput(input, {
        utilsScript: "/js/libs/tel-input-utils.js",
        customContainer: "w-100",
        initialCountry: "sa",
        onlyCountries: ['sd','sa', 'ae', 'qa', 'bh', 'om', 'kw', 'ye', 'jo', 'eg', 'ly', 'ma', 'mr'],
        preferredCountries: ['sd'],
        excludeCountries: ['il'], // except Israel 
        nationalMode: true,
        placeholderNumberType: "MOBILE",
        separateDialCode: true,
    });

var phone_number_without_plus_and_country_code = iti.getNumber().replace('+'+iti.getSelectedCountryData().dialCode,'')
```

**Comment by arshadinvoked** [comment]
@jackocnr how can we get the seprate both of values , first only dial country code without + sign and second only mobile number , we need these two values with diffrent variable can you please guid how can we do that .
