### ISSUE TITLE
User country lookup fail-safe fails

### ISSUE THREAD

**Issue by rderharo** [Bluefieldscom/intl-tel-input#136]
I wanted to test the fail scenario of making an outbound connection to ipinfo.io when setting `defaultCountry` to `auto`.

After directing ipinfo.io to 127.0.0.1 in my hosts file, I noticed that the plugin fails to call `_ready()` because the request seems to just hang with no response.

I wanted to open a pull request for this so in the `init` method I tried to change the default from `this.options.defaultCountry = ""` to:
`this.options.defaultCountry = this.preferredCountries.length ? this.preferredCountries[0] : this.countries[0];`

But this was before I realized that `_ready()` was not being called in the first place, and even if it did, the necessary objects were not yet initialized.

I also tried to add a `.fail()` callback to the GET request but that's when I realized the response was never coming back in the first place.

Do you have any ideas/suggestions? I don't yet know how realistic it is to simulate a blocked outbound connection via the hosts file, but I am trying to make sure that the fail-safe works even if there is a firewall rejecting the outbound connection.

**Comment by jackocnr** [comment]
That code uses the always() callback of $.get() which means it gets called in the case of success or error - I don't think there's anything else we can do.

Re: your pull request idea - I don't understand the point of changing that line - that stuff gets set in the _setInitialState method anyway...

**Comment by rderharo** [comment]
Yes, the problem is that in this case the always() callback never gets fired because the response never returns. I do not know why this happens, but I'm sure if you add ipinfo.io to your hosts file you'll get the same result.

My pull request was trying to have a default fallback set in case the request to ipinfo.io fails, but nevermind that. I realized that because the always() callback never gets fired if the response never returns, the plugin fails to initialize. That's the actual issue I should have been trying to solve.

**Comment by jackocnr** [comment]
Is this something that you're still planning to try and solve? I personally don't think we need to worry about handling the case where this call just hangs - I think it's very unlikely that will ever happen.

**Comment by rderharo** [comment]
Well, I was only trying to solve it because it was happening to me... But at this point the requirements for my app no longer necessitates the call to ipinfo.io so if you don't think it's worth solving then for now I guess we can just leave it alone. Thanks for the help.
