### ISSUE TITLE
Utils.js not cached

### ISSUE THREAD

**Issue by ganySA** [Bluefieldscom/intl-tel-input#137]
Hi

I think utils.js is a great feature. The one issue i have with it is that when i load it it doesnt seem to get cached in the browsers. Loading it once off wouldnt be too bad even at 200+ kb, but it seems that the way it is currently built it needs to load it every time? i am assuming it loads it on first init of intel input. 

It would be significantly better if it could somehow be cached by the browser.... loading 200kb every time is where the problem comes in.

Please correct me if i am wrong.

**Comment by jackocnr** [comment]
Hmm it definitely should be caching it. I changed it from `$.getScript()` to `$.ajax()` with `cache: true` which should do it. I'm not an expert on this tho... Could it be a problem with your dev setup?

**Comment by jackocnr** [comment]
BTW I've noticed that it is cached on the last production site I added it to. You just need to set a Cache-Control header for that file on your server.

**Comment by jackocnr** [comment]
I've now setup Cache-Control on the [demo site](http://jackocnr.com/intl-tel-input.html) and I can confirm that the utils.js is now cached in Safari (if you have visited this page before you may need to clear your cache in Safari to see the same results).

Can you confirm that the demo site is working for you?

**Comment by ganySA** [comment]
Will do some testing now! thanks for the prompt reply.

**Comment by ganySA** [comment]
Hi

You are indeed correct it is in the cache. I had the chrome 'Source' tab open and i was expecting to see it under source, it doesnt actually put it there. Howevever on the network tab it is caching it properly.

Thanks.

**Comment by jackocnr** [comment]
Great!
