### ISSUE TITLE
Flag reverts to local country

### ISSUE THREAD

**Issue by joshuawilson** [Bluefieldscom/intl-tel-input#138]
I have an sample app that is a basic contact form. I set up the intl-tel-input plugin and it works great until I go to edit the data I just added.

1. I add a phone number for another country (say the UK) and the correct flag appears.
2. I save the data.
3. Then I pull up the data in an edit version of the form and the flag has changed to USA.

If I edit the phone number it immediately updates the flag to the correct matching one.

Am I doing something wrong or is this an issue with the plugin?

**Comment by jackocnr** [comment]
In step 3, does the input contain the number before you initialise the plugin?

**Comment by joshuawilson** [comment]
Thanks for the quick feedback. :)

I tried moving the initialization around. 

If I have the initialization **before** the data is populated then the USA flag is displayed.
If I move the initialization **after** the data is populated then the correct flag is displayed but then I checked the other "contacts" and they have USA numbers but they do not have the USA flag.

**Comment by joshuawilson** [comment]
It appears that with the initialization after the data is populated, the first number I view sets it's flag as the default for all the others.

**Comment by joshuawilson** [comment]
I think I got it. 

I set a destroy for the data gets loaded and initialize after. So far so good.

Thanks for pointing me in the right direction.

And thanks for making such a great plugin! :+1:

**Comment by jackocnr** [comment]
Hmm I'm a bit confused, but yer you should call destroy when you're finished with the form.

I did a little test of 2 inputs with different numbers, and there was no problem with the flags: http://codepen.io/jackocnr/pen/ZYemag

Can you describe in more detail what your situation is, and how you fixed your problem? I just want to make sure it's not a bug...

**Comment by joshuawilson** [comment]
Sure, I think it easiest if I just point you at the code. If you want to run the code you can but it requires some set up that you can find on READMEs at higher levels. 

I first had the initialization for both the Add and Edit forms here:
https://github.com/joshuawilson/jboss-wfk-quickstarts/blob/WFK2-833/contacts-mobile-basic/src/main/webapp/js/validation.js#L175

Then I fixed it by moving the destroy and initialization for the Edit form to here:
https://github.com/joshuawilson/jboss-wfk-quickstarts/blob/WFK2-833/contacts-mobile-basic/src/main/webapp/js/app.js#L212

You maybe right that a better way to handle things is to destroy after the form is submitted, but by doing right before I populate the data I ensure everything is setup clean.

**Comment by jackocnr** [comment]
Hmm it's quite hard to see from such a complex codebase. Do you have a live example I could play with?
