### ISSUE TITLE
Bower install should include intl-tel-input/lib/libphonenumber/build/utils.js

### ISSUE THREAD

**Issue by goldensunliu** [Bluefieldscom/intl-tel-input#139]
For a while I was scratching my head on which util was missing from the bower install until I realized I needed libphonenumber. After giving up on how to compile my own libphonenumber from Google Closure, I realized there is a build version inside intl-tel-input/lib/libphonenumber/build/utils.js. I think it will be a good idea to roll up the utils.js into the bower install

**Comment by jackocnr** [comment]
Good thinking! All you need to do is add that file to the "main" section in the bower.json - could you do a pull request?

**Comment by goldensunliu** [comment]
yeah I can! I will do that

**Comment by jackocnr** [comment]
Ok I just added this in v4.0.2. Can you check it works?

**Comment by goldensunliu** [comment]
it works fine now if you want to use "bower list" command to chain your build process. Thanks! I apologize for the late reply and will contribute in the timely manner in the future!
