### ISSUE TITLE
Stripping country code in setNumber if nationalMode is on

### ISSUE THREAD

**Issue by rderharo** [Bluefieldscom/intl-tel-input#140]
This is more of a suggestion than anything, but based on my usage I've found that I would expect the country code to be stripped when I set the number via `setNumber()` when `nationalMode` is true.

The reason for this is because I have some screens that want fresh input and some that get pre-populated with the input that the user previously entered.

When `nationalMode` is on, if the user enters it without explicitly typing a country code then when they view the other screens later on it looks/behaves a bit weird when their number now includes an explicit country code. In addition, for +1 specific numbers, instead of (999) 888-8888 format they are now +1 999-888-8888.

Any thoughts about just using the country code in `setNumber()` to set the country and then stripping it from the string before setting the input value?

**Comment by jackocnr** [comment]
Good thought. But what if the user types out a full international number... would it be weird if when they come back, we have automatically converted it into a national number?

Ideally, they would see exactly what they entered, which is achievable, but you'd have to save both versions of the number: what they entered, as well as the full international version, which is annoying/unrealistic.

So overall, I think I'd be happy converting to national numbers when nationalMode is enabled. I think it's better than the alternative of having all of your national numbers turned into international numbers.

**Comment by jackocnr** [comment]
Added in v5.0.1.

**Comment by rderharo** [comment]
Thank you, it works great!
