### ISSUE TITLE
selectCountry and setNumber not working 

### ISSUE THREAD

**Issue by almogdesign** [Bluefieldscom/intl-tel-input#141]
Now of these of are working 

$("#mobile-number").intlTelInput("selectCountry", "gb");
$("#mobile-number").intlTelInput("setNumber", "+44 7733 123 456");

**Comment by jackocnr** [comment]
I just checked and they work on the [demo page](http://jackocnr.com/intl-tel-input.html). Can I see some code?

**Comment by almogdesign** [comment]
Yes of course 

I tried both options 
```javascript
  $("#orgPhoneNumber").intlTelInput({
    setNumber: "+44 7733 123 456"
  });
```

```javascript
  $("#orgPhoneNumber").intlTelInput("setNumber", "+44 7733 123 456");
```

Here is the screenshot 
![screen shot 2015-01-22 at 7 11 00 am](https://cloud.githubusercontent.com/assets/169507/5850890/19cc708e-a206-11e4-98c2-9a98bf058595.png)

Also note this does work 
```javascript 
$("#orgPhoneNumber").intlTelInput({
    defaultCountry: "auto"
  });
```

**Comment by almogdesign** [comment]
Here is the html 
```html
<div class="col-sm-6">
                                                <br>
                                                <label for="orgPhoneNumber">{{_ "orgPhoneNumber"}}</label>
                                                <input type="text" class="form-control" name="orgPhoneNumber" id="orgPhoneNumber"  data-parsley-required >
                                            </div>
```

**Comment by almogdesign** [comment]
@jackocnr I looked at the example code I don't think I'm doing anything different

**Comment by jackocnr** [comment]
Right so to initialise the plugin, you must call `$("#mobile-number").intlTelInput();` or you can start the plugin with some initialisation options (see the **Options** section of the readme) by passing in an object like this:
```js
$("#mobile-number").intlTelInput({
    defaultCountry: "gb",
    preferredCountries: ["fr", "gr"]
});
```

**Public methods** are different to options (again, see the readme), and are called like this: `$("#mobile-number").intlTelInput("setCountry", "gb");` only AFTER initialising the plugin.

Hope that clears things up?

**Comment by almogdesign** [comment]
So I tried the following initialising and then calling set country   and it does not work 
```javascript
  $("#orgPhoneNumber").intlTelInput();
  $("#orgPhoneNumber").intlTelInput("setCountry", "gb");
```

**Comment by jackocnr** [comment]
Works for me... http://codepen.io/jackocnr/pen/yehvE

**Comment by almogdesign** [comment]
Ok so the issue is with parsley.js I was first doing 
```javascript
// sets parsley form validation
  $('#form').parsley({trigger: 'change'});

  // sets parsley language
  window.ParsleyValidator.setLocale(TAPi18n.getLanguage());
```
and then calling intlTelInput. If I move it to the top everything works

**Comment by jackocnr** [comment]
Glad you resolved your issue. BTW I think I will change `selectCountry` to `setCountry` at some point to be more consistent.

**Comment by almogdesign** [comment]
Yea that does feel more correct

**Comment by archulal** [comment]
first initialise plugin after that add the setnumber code like below .
this will automatically select the country flag and display number in the field
var telInput = $("#phone"),
                    errorMsg = $("#error-msg"),
                    validMsg = $("#valid-msg");

                // initialise plugin
                telInput.intlTelInput({
                    utilsScript: "../../intlTelInput/build/js/utils.js"
                });
$("#phone").intlTelInput("setNumber", "+447733123456");

**Comment by jackocnr** [comment]
@archulal if you read the readme for `utilsScript` option, we advise using the `done` callback e.g.

```
input.intlTelInput({
    utilsScript: '...'
}).done(function() {
    // plugin has now finished initialising, so you're good to call setNumber etc
});
```

**Comment by archulal** [comment]
or we cal simply set by value="+447733123456"

**Comment by devteam-technolabs** [comment]
You can do this using below code.
let phoneInput = document.querySelector("#update_phone_number");
let phoneInstance = window.intlTelInput(phoneInput, {
    autoPlaceholder: "off",
    separateDialCode: true,
    initialCountry: "US"
});

 phoneInstance.setCountry("in", true);
