### ISSUE TITLE
Adjust flag alignment 

### ISSUE THREAD

**Issue by almogdesign** [Bluefieldscom/intl-tel-input#142]
Been trying to adjust the flag alignment with some custom CSS however noting is working. How is this set or what CSS class is setting this. 

I tried using 

.intl-tel-input .selected-flag 

Here is my current issue 
![screen shot 2015-01-22 at 11 03 14 am](https://cloud.githubusercontent.com/assets/169507/5852949/c088ad14-a226-11e4-8b54-2799d9d95b21.png)

**Comment by jackocnr** [comment]
It must be your custom CSS causing that as the alignment works on the demo page. You will need to inspect the element using Chrome Dev Tools (etc) to see which CSS rules are causing that.

**Comment by almogdesign** [comment]
Yes didn't see anything well check again
