### ISSUE TITLE
Canadian numbers recognized as US if prefixed by country code

### ISSUE THREAD

**Issue by rileyjshaw** [Bluefieldscom/intl-tel-input#143]
Canada and the US share a country code (+1). The library handles the distinction if a number is prefixed with a `+1` or no country code at all, but fails if numbers are prefixed with a `1`.

Steps to reproduce:

 - Navigate to http://jackocnr.com/intl-tel-input.html
 - Select Canada from the country dropdown.
 - Type "1647" into the text field.
 - The country dropdown will change to the United States.

In contrast, libphonenumber demos seem to yield the correct results. E.g.:

 - Navigate to http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
 - Enter the phone number "1647*******".
 - Enter the default country "US".
 - Click Submit.

The validation results show "Phone Number region: CA"

**Comment by jackocnr** [comment]
Hmm good spot. I wasn't aware that you would dial the 1 without the plus, but I have just confirmed that with my American colleague! I will fix this when I have time. I'm also open to pull requests if you're in a hurry!

**Comment by jackocnr** [comment]
Fixed in v5.0.3

**Comment by rileyjshaw** [comment]
Awesome - thanks!
