### ISSUE TITLE
isPossibleNumber is not a function

### ISSUE THREAD

**Issue by ellimccale** [Bluefieldscom/intl-tel-input#1456]
![image](https://github.com/jackocnr/intl-tel-input/assets/6090263/e485ade7-332e-43ef-943a-ca47ecaae239)

### Steps to reproduce
1.  Go to [this CodePen](https://codepen.io/ellimccale/pen/JjwPoyq/bb2e77ea55387a6c44bdc76abf788efe)
2.  Enter any known valid phone number in the field
3.  Click the "Validate" button
4. Watch the console logs

### Expected behaviour
The console should log `likely valid` and a TypeError should not be present when using this method.

### Actual behaviour
`Uncaught TypeError: iti.isPossibleNumber is not a function`

### Initialisation options
Default options using the "Getting Started" steps in this repo and the code from "Validation (Practical)" on the project's website.

NOTE: This CodePen seems to be setup correctly - other methods, such as `isValidNumber()`, work as expected; i.e., no TypeErrors.

**Comment by ellimccale** [comment]
Thanks! Might consider updating your README. It's still using 18.1.1.

**Comment by jackocnr** [comment]
Thanks, done 👍
