### ISSUE TITLE
Object doesn't support property or method 'always'

### ISSUE THREAD

**Issue by ekoome** [Bluefieldscom/intl-tel-input#147]
On Internet Explorer 11, I'm getting the following error message:

SCRIPT438: Object doesn't support property or method 'always'
File: intlTelInput.min.js, Line: 5, Column: 875

Here is how I'm calling it:
$('input[name=phone]').intlTelInput({
						defaultCountry: "auto",
						responsiveDropdown: true,
						preferredCountries: ["us","gb"],
						utilsScript:"/javascript/utils.js"
				
				});

Any thoughts on the issue?

**Comment by jackocnr** [comment]
That's very strange! That `always` call is part of jQuery... Do you still see the error if you initialise the plugin without any options?

Maybe try the unminified version of the plugin as well, just to check it's not a problem there.

**Comment by ekoome** [comment]
Fixed by using latest Jquery CDN.

By the way, how does one display country code  in the input box (+44 etc)? This was available a few months back.

**Comment by jackocnr** [comment]
Set `nationalMode` to false if you want users to have to enter international dial codes. Can I ask why you want this?

**Comment by dijashub** [comment]
@jackocnr  this is observed in IE10 and Edge

   var primaryContact = document.querySelector("#primaryContactTel");
	var itiPrimary = window.intlTelInputGlobals(primaryContact, {
		utilsScript:/scripts/utils.js",
	})

Console Error : Object doesn't support property or method 'intlTelInput'

any help please??
