### ISSUE TITLE
Tweaking base css to allow better alignment within a input-group

### ISSUE THREAD

**Issue by gegere** [Bluefieldscom/intl-tel-input#148]
Allow input field to use `<div class="input-group">` around it. 

Great widget!

I am looking to have the input field nicely line up against a call button. This is the tweaked CSS to have the country drop down list align correctly within the field and have a button bump up against the right side. The problem seems to be with a iOS device the input field is not selectable. I can't reproduce this with a Safari browser as it the input field is selectable. Here is a screenshot using the iOS device simulator, click select inside the input box: http://cl.ly/image/2O070x10373m

Everything looks good with the style but I can't select the input field via a iOS device. Here is the changed CSS.

```
.intl-tel-input {
    display: block;
    position: initial;
}
```

This is what the UI looks like via the initial CSS when trying to use "input-group": http://cl.ly/image/3U1G2U1s3l3M

To test and override my custom CSS in CodePen add the following CSS
```
#phone .intl-tel-input {
    display: inline-block;
    position: relative;
}
```

**Comment by jackocnr** [comment]
If you look at how Bootstrap styles the `<input>` element, it uses `display: table-cell;`, so I tried applying that to the `.intl-tel-input` container and it worked. Example here: http://codepen.io/jackocnr/pen/pvdgrO

**Comment by gegere** [comment]
So the example I had worked regarding the styling. The problem is using iOS, is trying to input data or clicking the flag menu and selecting an option. **You can't.**

This is the issue, and I am after a solution. I will test the rendered page tomorrow. I believe I tested all element block types. I give it a stronger, deeper test.

**Comment by gegere** [comment]
Hello Jack, following back up on this. I am sure you are busy I didn't read this over in detail and thought I was focused on the UI style / interface as an issue.

So the example I had worked looks great but does not function. **The problem is** when using `<div class="input-group">` on iOS it is trying to capture inputs and not allowing a click  to the flag / menu.

If have taken a [screencast](http://cl.ly/1R3Q0e0Y142o) to let you view the experience.

I would be happy to help get to the bottom of this.

**Comment by jackocnr** [comment]
Ok I have reproduced this on an iPhone - if you view the codepen on Safari then you can't open the flag dropdown and you can't even focus the input. If you view it on Chrome (on iOS) it works fine.

If I had to guess I would say this must be a bootstrap issue, but it requires further investigation.

**Comment by gegere** [comment]
Happy to hear, yes this is correct. This issue it specific to **iOS / Safari**. Since you manage this repo I can go more in-depth into the bootstrap setup & debug.

If I remove the `class="form-control"` from the input field the **country dropdown** does work correctly but the styling is *not ideal*.

**Comment by gegere** [comment]
Purposed a solution in the README.md. Happy with solution!
