### ISSUE TITLE
Please make dropdown width match input field

### ISSUE THREAD

**Issue by girtsl** [Bluefieldscom/intl-tel-input#149]
Please make dropdown width match input field's width and expand only if a country entry is wider than that.

If I'm not mistaken, previously this was handled by the `responsiveDropdown` option which was dropped in v4.0.0.

If you only have a couple of countries, the dropdown is unnecessary wide, hides other content and simply looks ugly: 
![2015-02-03_11-10-55](https://cloud.githubusercontent.com/assets/6348534/6017452/6bb06a6a-ab96-11e4-9ac4-bf2ecb66dfc4.png)

Before v4.0.0.0: 
![2015-02-03_11-11-08](https://cloud.githubusercontent.com/assets/6348534/6017458/776e65b4-ab96-11e4-9cca-c8f3427f0d7f.png)

**Comment by jackocnr** [comment]
I've just figured out that we can use `white-space: nowrap;` instead of setting the width on the `<ul>` and then it will only be as wide as the content. You can add it yourself for now, along with overriding the width by setting it to `auto`. I will add this in the CSS soon.

**Comment by jackocnr** [comment]
Fixed in v5.1.4

**Comment by girtsl** [comment]
Thanks!

**Comment by troggy** [comment]
Looks like it doesn't work again in 7.0.0

**Comment by jackocnr** [comment]
First of all, the latest version is v7.0.2, which is the version on the [demo page](http://jackocnr.com/intl-tel-input.html), where it appears to be working to me. Using Chrome dev tools, I see that the dropdown width is 413px, and if you open the dropdown, scroll down to the widest element ("Saint Pierre...") and inspect that list item in chrome dev tools, and remove it, then you will see the whole dropdown goes down to 409px wide.

**Comment by szukaiLee** [comment]
When I set full width input, that provided in Troubleshooting
.intl-tel-input {width: 100%;}

The dropdown does not follow the input width.

**Comment by daviscabral** [comment]
I am using the version 12.1.6, and is not working anymore. Anyone has a simple fix?
