### ISSUE TITLE
defaultCountry:auto is not triggering change onload

### ISSUE THREAD

**Issue by petrce** [Bluefieldscom/intl-tel-input#152]
this means there is no way how to extract country/dial code get by auto function

fix should by easy, just add "this.telInput.change();" in the end of "_ready: function() {..."

**Comment by jackocnr** [comment]
Thanks for reporting this. Can you explain your use case?

**Comment by jackocnr** [comment]
I don't think it makes sense to trigger "change" in this case as we're still initialising the plugin. Instead I think we should support the .done() callback. See https://github.com/Bluefieldscom/intl-tel-input/issues/168.

**Comment by petrce** [comment]
yes you are right, I had a small javascript callback added to change extracting telcode to different field - is there better way how to do that? - send number(without telcode) in one field and telcode in another?
thanks

**Comment by jackocnr** [comment]
If you set nationalMode to true (this is the default in the latest version of the plugin), users are expected to just enter their national numbers (no international dial code). You can then extract the dial code for the currently selected country using `getSelectedCountryData` (see readme).
