### ISSUE TITLE
Deffered object

### ISSUE THREAD

**Issue by ekoome** [Bluefieldscom/intl-tel-input#153]
I would like to do some things when InTelInput has finished its setup, for example, when class int-tel-input is available. 

I have tried .done() but get an error that IntlTelInput does not have function done().

Any thoughts?

**Comment by jackocnr** [comment]
The only asynchronous part of the initialisation is with `defaultCountry: "auto"` so if you're not using that, you should be good to assume the plugin is ready to go in the next JS statement e.g.

```js
$("input").intlTelInput();
$("input").parent().hasClass("intl-tel-input"); // this should be true
```

Does that work for you? But I should add something for the async situation. I'm just short on time atm, so I'm open to pull requests ;)

**Comment by jackocnr** [comment]
Ok I've bundled this with some other issues around setting defaultCountry to "auto" - see https://github.com/Bluefieldscom/intl-tel-input/issues/168.

**Comment by girtsl** [comment]
Hi,
Although this is a welcome change it should have increased the major version number as it breaks the existing behavior of returning a jQuery object.
