### ISSUE TITLE
Accept uppercase value in 'selectCountry' method

### ISSUE THREAD

**Issue by girtsl** [Bluefieldscom/intl-tel-input#154]
This makes life easier for those of us who chose to use various ISO codes in uppercase.
The required change would be to simply convert the parameter value to whatever case you need to compare with.

Thanks,
Girts

**Comment by jackocnr** [comment]
Hmm if we do it with `selectCountry` we'd also need to do it with `defaultCountry`, `onlyCountries`, and `preferredCountries`. I'm just not sure this is the responsibility of the plugin? And I'm afraid of adding bloat. Is this common practice for jquery plugins? Can you give examples of others who do this?

**Comment by girtsl** [comment]
I'm not sure about the common practice for jquery plugins but in all sources I could find, the ISO code is referenced simply as "code" (without reference to letter case) and is written in uppercase. Given that the example from official site (https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) also has them in upper case I would assume that's the way to go. Please correct me if I'm wrong and you have a more authoritative source.

May I ask, why did you choose to store them in lower case? There is no difference in storage space or performance-wise that I know.

In any case, the data storage is an implementation detail, my suggestion is more about the [robustness principle](http://en.wikipedia.org/wiki/Robustness_principle) - `Be conservative in what you do, be liberal in what you accept from others`.

**Comment by jackocnr** [comment]
I used lower case because that's a standard way to store information that is not case-sensitive. We're also using these codes as CSS classnames, where again the standard is lower-case. Also that's what [Flag Sprites](http://www.flag-sprites.com/) do, which is where we get our flags, so it needed to work with that.

But you're right, it's much better to allow either, and it was an easy fix, so I did it. Fixed in v5.1.5.

Thanks for raising the issue.

**Comment by girtsl** [comment]
Thanks!

**Comment by Rvanlaak** [comment]
So to conclude: `defaultCountry` should be lowercase? A note about that in the readme would be nice :+1:

**Comment by jackocnr** [comment]
Nope, it can be either upper or lower case.
