### ISSUE TITLE
Option 'autoPlaceholder' is ignored (example number is always added)

### ISSUE THREAD

**Issue by girtsl** [Bluefieldscom/intl-tel-input#155]
The example number is always added, if the utils script is loaded.
Looking in the source code, the `autoPlaceholder` option's value is never read.

A workaround is to set the placeholder to a whitespace value (empty string will not work) which sets hadInitialPlaceholder to true and thus prevents the plugin from setting the example number placeholder.

**Comment by jackocnr** [comment]
Are you sure you're using the latest version? It's working here: http://codepen.io/jackocnr/pen/ByweYb

**Comment by girtsl** [comment]
You are right, I had v5.0.0 not v5.0.3. Thanks!
