### ISSUE TITLE
Output International format doesn't change when country dropdown selected.

### ISSUE THREAD

**Issue by leecollings** [Bluefieldscom/intl-tel-input#156]
When using the International format example, the correct format is only outputted if the country selection occurs before the number entry.

eg. On page load, if a country is selected in dropdown, and then number is typed, the format is correctly changed. Then, if the number is left in the input field, but country selection is changed, the output string does not update, and remains with the old International code appended.

**Comment by jackocnr** [comment]
Oh I see - this is just a problem with the example code, not the plugin itself. The example code only updates the international number on the `keyup` event. I will change it to update on both `keyup` and `change`, which is fired when you select a different country.

**Comment by leecollings** [comment]
Awesome. Are you able to give an idea as to when this change will happen?

**Comment by jackocnr** [comment]
I'm not sure - I'm quite busy at the moment. I'm open to pull requests ;)

**Comment by jackocnr** [comment]
Fixed.
