### ISSUE TITLE
Minimize utils.js

### ISSUE THREAD

**Issue by alexeevnick** [Bluefieldscom/intl-tel-input#158]
There is massive database of countries, but i want to use just 3 of them.
Where I can find documentation of this var so i can cut useless data for me?
Thank you.

**Comment by jackocnr** [comment]
utils.js is a custom build of [libphonenumber](https://github.com/googlei18n/libphonenumber/) based on [this source file](https://github.com/Bluefieldscom/intl-tel-input/blob/master/lib/libphonenumber/src/utils.js). I don't know if there's a way to specify which country data you want to include - you'd have to speak to them about that.
