### ISSUE TITLE
Unneeded dial codes, eg (0) in UK

### ISSUE THREAD

**Issue by wamatt** [Bluefieldscom/intl-tel-input#163]
Suppose we have a number like here:

http://www.barclays.co.uk/ContactUs/Callus/P1242557966951

![image](https://cloud.githubusercontent.com/assets/1271434/6225590/5a47e482-b641-11e4-8a7f-18585b389ec8.png)

If a user pastes in this "+44 (0)1604 230 230", it might be nice to remove the national dial code automatically.

Currently this is what happens.

![image](https://cloud.githubusercontent.com/assets/1271434/6225602/80c0833a-b641-11e4-994e-d5188d9b4d39.png)

resulting in an invalid number. Also not sure how hard it would be to implement this, or if it will create other issues?

thanks for your  consideration @jackocnr :)

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for all formatting stuff, and their "AsYouTypeFormatter" [can't handle](https://github.com/googlei18n/libphonenumber/issues/366) numbers in this format. But if the user pastes a valid number, we could use the regular number formatter to extract the standardised number (i.e. no leading '0') and use that instead. But it would mean running a full number validation/conversion on every paste event (and the current logic for catching a paste event is on any meta keyup).

Anyway, I would be up for including this extra logic, but I don't have time to implement it myself. I'm open to pull requests though, or I could make time if you or your employer would be willing to sponsor the feature?

**Comment by FesterCluck** [comment]
The national mode example here seems to provide part of what you are looking for.

http://jackocnr.com/lib/intl-tel-input/examples/gen/national-mode.html

The international version above the input removes the 0.

**Comment by FesterCluck** [comment]
I've got a hunch the solution to this problem is going to be the same as for https://github.com/Bluefieldscom/intl-tel-input/issues/159

**Comment by wamatt** [comment]
thanks for investigating @jackocnr. if you have a look at @FesterCluck's comment below, it looks like it's possible without too much effort?

![image](https://cloud.githubusercontent.com/assets/1271434/6242097/22f6dcf8-b6dd-11e4-82bc-7d841dede927.png)

It would appear to have converted it correctly to e.164 (the first line above the text box).

that said you may already know this, and quite possible I'm missing something (given I'm not too familiar with the inner workings of libphonenumber)

**Comment by jackocnr** [comment]
Yer as I say, the logic is: on paste: check if it's a valid number, and if it is, replace it with the proper formatted version (national/international depending on the value of the nationalMode setting).

Or rather, do what I do in the example code and just try formatting it straight away and see if that returns anything.

But as I say, I don't have any spare time right now.

**Comment by wamatt** [comment]
np, understood. time is in short supply!
