### ISSUE TITLE
Pretty national formatting for non US numbers

### ISSUE THREAD

**Issue by wamatt** [Bluefieldscom/intl-tel-input#164]
Looks good :)

![image](https://cloud.githubusercontent.com/assets/1271434/6225820/2089dc52-b644-11e4-84bd-f321bb3abad4.png)

Switch to another country, eg ZA(South Africa) and it comes out like this

![image](https://cloud.githubusercontent.com/assets/1271434/6225845/554a0084-b644-11e4-9d95-0aec54339643.png)

Should look this this:

![image](https://cloud.githubusercontent.com/assets/1271434/6225922/0c414bbc-b645-11e4-9cc1-7dc027d55dd3.png)

AFAICS the above representation would also be consistent with the national format in PhoneNumberMetadata.xml from libphonenumber.

**Comment by jackocnr** [comment]
Hmm which version are you using? I can't recreate this on the [demo site](http://jackocnr.com/intl-tel-input.html).

**Comment by wamatt** [comment]
OSX Yosemite and Chrome Version 41.0.2272.53 beta (64-bit)

I'm using the demo site you mentioned to test..

**Comment by wamatt** [comment]
tested in latest Safari and Firefox. Can reproduce in all 3 browsers.

**Comment by wamatt** [comment]
Also related. If you select a country other than US, then it won't allow you to input spaces or dashes as you type, however it works fine if US is selected.

Might be nice to have all countries inputting in their local style, or at very least to allow the same formatting as US

**Comment by jackocnr** [comment]
Ah I thought you meant type the US number, leave it in the input and switch to ZA!

Ok yer if you select ZA then enter 0211234567 then you get 021 123 4567 yer. We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, and that is how they format that number. You can test directly with them by going to their [demo site](http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html) and entering that number along with the ZA country code and submitting. You will see under the "Formatting Results" section, that is how they format that as a national number. If that is incorrect, you should file an issue with them.

Also re: the spaces and dashes in the US number - it actually doesn't let you add any of those chars yourself, it's just that if you happen to type them where libphonenumber wants them then it adds them for you. If you try and add them in different places you will see it wont work.

**Comment by jackocnr** [comment]
I'm going to close this - let me know if you have any other questions.

**Comment by wamatt** [comment]
no problem. it's definitely an issue, and is not formatting correctly. there are other countries other than the US ;) 

unfortunately I don't have time to champion this with libphonenumber. so lets keep it closed then.

**Comment by jackocnr** [comment]
Can you provide a link to backup your claim of how South African numbers should be formatted?

**Comment by wamatt** [comment]
well, my point wasn't really about South Africa per se, but rather I don't think anyone would contest no other countries use *any* formatting. eg

XXXXXXXXXXX

I grew up there but now live in the US, so maybe things are changing. This guide here explains my experience and understanding of the "right way" to do it

http://www.ee.co.za/wp-content/uploads/2013/09/ee-publishers-style-sheet.doc

![image](https://cloud.githubusercontent.com/assets/1271434/6338464/f852a23a-bb63-11e4-91e8-c558406fe807.png)

On the other hand a university guide has it without brackets

http://www0.sun.ac.za/taalsentrum/assets/files/Style%20Guide%202014%20final%20for%20web.pdf

![image](https://cloud.githubusercontent.com/assets/1271434/6338504/38f0a490-bb64-11e4-9371-661f8641018a.png)

And further more Google searches reveal many other options in the wild

https://www.google.co.za/search?hl=en&cr=countryZA&safe=off&biw=1777&bih=861&tbs=ctr%3AcountryZA&q=contact+us&btnG=&oq=&aq=&aqi=&aql=&gs_l=&gws_rd=ssl#cr=countryZA&safe=off&hl=en&tbs=ctr:countryZA&q=contact+us+011

https://www.google.co.za/search?hl=en&cr=countryZA&safe=off&biw=1777&bih=861&tbs=ctr%3AcountryZA&q=contact+us&btnG=&oq=&aq=&aqi=&aql=&gs_l=&gws_rd=ssl#cr=countryZA&safe=off&hl=en-ZA&tbs=ctr:countryZA&q=contact+us+021

From my quick assessment it seems the brackets and dashes are much less popular in practice, than my memory serves. That's pretty interesting!

However there is as least one common (and I'd wager universal concept). Use spacing!

XXX XXX XXXX or
XX XXX XXXX etc

And not this

XXXXXXXXXX

Which is pretty much terrible from a UI perspective across all cultures.

**Comment by jackocnr** [comment]
I don't understand. It does insert spacing for south Africa, as seen in your first message.

**Comment by wamatt** [comment]
ahh ok, I was using (650) 123 4567 as an example.

In that case it will have no spacing. But that makes sense because 650 is not a valid city code in South Africa.

![image](https://cloud.githubusercontent.com/assets/1271434/6339172/eee9ab9e-bb68-11e4-930c-9c6c75740677.png)

I clicked around on a few other countries and none had spacing (using the number above), so wrongly assumed no other countries had spacing or formatting.

Feel like a complete idiot now! thanks for the your patience :)

**Comment by jackocnr** [comment]
Haha no worries. I've made the same mistake before.
