### ISSUE TITLE
why am i seeing a light grey border around the dropdown arrow in FF35.0.1

### ISSUE THREAD

**Issue by ahsanpervaiz** [Bluefieldscom/intl-tel-input#167]
![whyborder](https://cloud.githubusercontent.com/assets/5106455/6318257/6fc497f2-baaa-11e4-8a29-bc035bccc506.png)

I am a novice compared to you guys but doesn't this border around the dropdown arrow irritates you...If it is not possible, use png image for arrow rather than css arrow....
I am using Firefox 35.0.1 on Win7, and this problem is seen only in Firefox not in Chrome or IE11 so it is related to Firefox so please update your css to remove this border
Thanks

**Comment by jackocnr** [comment]
Thanks for reporting this. It is due to a bug in FF. Fixed in v5.4.1.
