### ISSUE TITLE
Add CC to Phonenumber automatically

### ISSUE THREAD

**Issue by Silikowski** [Bluefieldscom/intl-tel-input#170]
Is there an option to automatically add the Countrycode of the country i choose to the number entered?

For example: i changed the Country to UK (+44) and insert the number the placeholder shows (07400...) to pass it via POST.
Now i get 07400... in my POST-Var.

Is there any way to update the leading 0 via the Flagpicker so the form will POST +447400...?

**Comment by jackocnr** [comment]
You can use the `getNumber` method to get the full international telephone number (inc country code).

If you're submitting the form with Ajax then you obviously have complete control over what value you send. If you're using an old-fashioned HTML form to submit, then you need an `<input>` to contain the final value, so I would advise copying the functionality of the [nationalMode example](http://jackocnr.com/lib/intl-tel-input/examples/gen/national-mode.html) and on every keyup event, calling `getNumber` and putting the result in a hidden input, and then use that POST value on your server instead.

**Comment by jackocnr** [comment]
FYI I added some information about this to the Troubleshooting section of the readme, along with an example.
