### ISSUE TITLE
default options runs fine, as soon as custom options entered, utility JS file isn't loaded

### ISSUE THREAD

**Issue by leecollings** [Bluefieldscom/intl-tel-input#172]
All the files are copied and referenced correctly, the plugin works fine if just using the default init line:

`$("#phone").intlTelInput();`

But whenever I even start to put brackets inside it, to provide custom settings, it breaks and doesn't load at all display an error `Uncaught TypeError: Cannot read property 'extend' of undefined`. This will also happen when providing no custom settings but still including brackets like:

`$("#phone").intlTelInput({});`

**Comment by jackocnr** [comment]
Hmm I can't reproduce this. What version of the plugin are you using? And which browser/version on which OS/version?

**Comment by leecollings** [comment]
I'm running 5.6.1 (written in the JS file) using Google Chrome Version
40.0.2214.115 m on Windows 7

On Mon, Mar 2, 2015 at 4:17 PM, jackocnr <notifications@github.com> wrote:

> Hmm I can't reproduce this. What version of the plugin are you using? And
> which browser/version on which OS/version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-76741821>
> .
>



-- 
Regards,

*Lee*

**Comment by jackocnr** [comment]
Are you using the minified script (ending .min.js) or the normal one?

**Comment by leecollings** [comment]
The minified

On Mon, Mar 2, 2015 at 4:39 PM, jackocnr <notifications@github.com> wrote:

> Are you using the minified script (ending .min.js) or the normal one?
>
> On 2 Mar 2015 08:19, "leecollings" <notifications@github.com> wrote:
>
> > I'm running 5.6.1 (written in the JS file) using Google Chrome Version
> > 40.0.2214.115 m on Windows 7
> >
> > On Mon, Mar 2, 2015 at 4:17 PM, jackocnr <notifications@github.com>
> wrote:
> >
> > > Hmm I can't reproduce this. What version of the plugin are you using?
> And
> > > which browser/version on which OS/version?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-76741821
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Regards,
> >
> > *Lee*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-76742338
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-76746695>
> .
>



-- 
Regards,

*Lee*

**Comment by jackocnr** [comment]
Do you see the problem on [this Codepen](http://codepen.io/jackocnr/pen/yehvE)?

What exactly do you mean by "it breaks and doesn't load at all"? The plugin doesn't initialise? You don't see the selected flag or the arrow at all?

**Comment by leecollings** [comment]
It appears as though it doesn't initialise. The input form just appears
blank, as though its a normal input field. There's no dropdown, or flag.

I also get a console error 'Uncaught TypeError: Cannot read property
'extend' of undefined'.

On Mon, Mar 2, 2015 at 5:37 PM, jackocnr <notifications@github.com> wrote:

> Do you see the problem on this Codepen
> <http://codepen.io/jackocnr/pen/yehvE>?
>
> What exactly do you mean by "it breaks and doesn't load at all"? The
> plugin doesn't initialise? You don't see the selected flag or the arrow at
> all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-76759008>
> .
>



-- 
Regards,

*Lee*

**Comment by leecollings** [comment]
The issue isn't on that codepen by the way, it seems to load up fine there. But for some reason whenever I enter the two curly brackets in the init.js file, it stops loading, and doesn't load any JS after it it seems.

**Comment by jackocnr** [comment]
You should load the utils using script the `utilsScript` option to make sure it's non-blocking.

I've looked through the source and the only place we call `extend` is on the jQuery object, so it must be a problem with that. Are you definitely including jQuery before the plugin script?

**Comment by leecollings** [comment]
Yeah, jQuery is being called before, as part of wp_enqueue_script. It may
be worth mentioning that this is all within Wordpress, if that makes a
difference? I did try using the utilsScript, but when I did it didn't make
any change. I'll have another go and will update you.

On Tue, Mar 3, 2015 at 4:14 PM, jackocnr <notifications@github.com> wrote:

> You should load the utils using script the utilsScript option to make
> sure it's non-blocking.
>
> I've looked through the source and the only place we call extend is on
> the jQuery object, so it must be a problem with that. Are you definitely
> including jQuery before the plugin script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-76976520>
> .
>



-- 
Regards,

*Lee*

**Comment by jackocnr** [comment]
Seeing as how the Codepen works I'm going to assume this is an issue with Wordpress and jQuery, so I'm going to close this for now. Feel free to re-open if you think this is an issue with the plugin (in which case please post a link to a reduced test case on Codepen etc).

**Comment by leecollings** [comment]
I believe this is the way that Wordpress uses jQuery in noConflict mode..
which means that the utilsScript is referencing $, which cannot be read (as
it makes Wordpress recognise jQuery instead.) I'll see if I can add a
noConflict wrapper to the JS file, although this will be a hack, and
shouldn't edit the files of the plugin at all. (What I'm getting at is that
I'm sure there could be something added to the plugin to make it noConflict
useable).

On Tue, Mar 3, 2015 at 5:40 PM, jackocnr <notifications@github.com> wrote:

> Closed #172 <https://github.com/Bluefieldscom/intl-tel-input/issues/172>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#event-245377410>
> .
>



-- 
Regards,

*Lee*

**Comment by leecollings** [comment]
With this line in the init.js file:

$("#phone").intlTelInput('utilsScript', 'intl-tel.utils.js');

Is the path for the utilsScript, relative to the init file? I think I'm
getting closer, as I'm getting no JS errors, and all files are loading
now.. but there's still nothing showing up in the text input field.

On Wed, Mar 4, 2015 at 11:03 AM, Lee Collings <lee@leecollings.co> wrote:

> I believe this is the way that Wordpress uses jQuery in noConflict mode..
> which means that the utilsScript is referencing $, which cannot be read (as
> it makes Wordpress recognise jQuery instead.) I'll see if I can add a
> noConflict wrapper to the JS file, although this will be a hack, and
> shouldn't edit the files of the plugin at all. (What I'm getting at is that
> I'm sure there could be something added to the plugin to make it noConflict
> useable).
>
> On Tue, Mar 3, 2015 at 5:40 PM, jackocnr <notifications@github.com> wrote:
>
>> Closed #172 <https://github.com/Bluefieldscom/intl-tel-input/issues/172>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#event-245377410>
>> .
>>
>
>
>
> --
> Regards,
>
> *Lee*
>



-- 
Regards,

*Lee*

**Comment by jackocnr** [comment]
`utilsScript` is an initialisation option, which means it must be passed in as part of an object (see the code in [this example](http://jackocnr.com/lib/intl-tel-input/examples/gen/is-valid-number.html)). It's got nothing to do with your script file - it's relative to the page you're on (again, see the example).

I'll re-open this issue while we investigate the noConflict thing. FYI, when the script is first loaded on the page (before you actually initialise the plugin), it accesses the `jQuery` variable (see [this line](https://github.com/Bluefieldscom/intl-tel-input/blob/master/build/js/intlTelInput.js#L12)), and passes it into a function, which gives that argument the name `$`. The point is that you need to have the global `jQuery` ready when you load the script file.

**Comment by jackocnr** [comment]
BTW do you have a link to the site? Or some testing version or something so I can see the code?

**Comment by jackocnr** [comment]
If I were you, the way I would debug this is to open the plugin script in Chrome dev tools (probably easier if you use the unminified version), and put a break point on that line that I linked to above, and check what the value of `jQuery` is at that point. (also good to note what version of jQuery you're using).

**Comment by leecollings** [comment]
There is a testing version of the site at http://dev.bellavou.co.uk/contact-us/enquiry-form

**Comment by leecollings** [comment]
Hi Jack, Just to give you an update on this. I believe I've got the plugin working okay. I think it was a path issue with the utils.js file when trying to include it manually.

Now it seems that the file is being included fine, and the appearance of the input is as expected, with arguments now being applied when calling the plugin.

**Comment by jackocnr** [comment]
I can't see the plugin on that site you posted.

As a note: I see that on that page, jQuery is defined, but $ is not.

**Comment by leecollings** [comment]
Maybe the plugin hasn't been put into that Dev version, sorry.

Also the way that Wordpress works is that it runs in noConflict mode, where
it uses jQuery instead of $.

You wrap all your standard $ code with something that converts, then you
can continue to use $ and it will run it as jQuery.

It's running fine on my local copy now, so I believe it was because the
utils file wasn't being loaded properly.

On Friday, 13 March 2015, jackocnr <notifications@github.com> wrote:

> I can't see the plugin on that site you posted.
>
> As a note: I see that on that page, jQuery is defined, but $ is not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/172#issuecomment-79034288>
> .
>


-- 
Regards,

*Lee*

**Comment by jackocnr** [comment]
Ok well I'm glad to hear it's working. I would really appreciate a link when it's live.

**Comment by brada1703** [comment]
Hey Lee, 

Do you mind posting how you fixed it? I am still running into this problem.


Thanks!

> Maybe the plugin hasn't been put into that Dev version, sorry.
> 
> Also the way that Wordpress works is that it runs in noConflict mode, where
> it uses jQuery instead of $.
> 
> You wrap all your standard $ code with something that converts, then you
> can continue to use $ and it will run it as jQuery.
> 
> It's running fine on my local copy now, so I believe it was because the
> utils file wasn't being loaded properly.
>
