### ISSUE TITLE
Improve when defaultCountry is auto

### ISSUE THREAD

**Issue by lucaspfsd** [Bluefieldscom/intl-tel-input#174]
Hi I suggest a improve in check ipinfo, using cookies to dosen't make many request of same user: for example, this is the code that I need implement in your framework:
```javascript
init: function() {
            var that = this;
            // if defaultCountry is set to "auto", we must do a lookup first
            if (this.options.defaultCountry == "auto") {
                var cookieDefaultCountry = $.cookie("defaultCountry");

                if (cookieDefaultCountry != null) {
                    var jsonDefaultCountry = JSON.parse(cookieDefaultCountry);
                    this.options.defaultCountry = jsonDefaultCountry.country.toLowerCase();

                    this._ready();
                }
                else {
                    // reset this in case lookup fails
                    this.options.defaultCountry = "";
                    var ipinfoURL = "http://ipinfo.io";
                    if (this.options.ipinfoToken) {
                        ipinfoURL += "?token=" + this.options.ipinfoToken;
                    }
                    $.get(ipinfoURL, function (response) {
                        if (response && response.country) {
                            that.options.defaultCountry = response.country.toLowerCase();
                            $.cookie("defaultCountry", JSON.stringify(response), { path: '/', expires: 30 });
                        }
                    }, "jsonp").always(function () {
                        that._ready();
                    });
                }
            } else {
                this._ready();
            }
        },
```
Note that I'm checking if cookie is empty, to request the ipinfo API.

And the freegeoip api is more powerfull than ipinfo, so is better to check ips, because, ipinfo the max request is 1,000 per day and freegeoip is 10,000 per hour. ;)

That is it, thanks.

**Comment by jackocnr** [comment]
Re: multiple ip lookups for same user: I've actually changed how this system works in the latest version - we now only do 1 lookup per page, and it doesn't block the initialisation of the plugin. But we will still do a new lookup on each page, so the cookie solution would be better and I would have already done that BUT: it relies on the jQuery cookie plugin, which I don't want to bundle into this plugin.

Tho I've just thought: we could check if they happen to have the cookie plugin loaded (which most sites probably do) and in that case use your solution? I'd be open to a pull request that did that. Something like `if ($.cookie) {...}`.

Re: the max requests per day: remember it's the user making the requests, not your server, so it's 1000 requests per user per day, which is surely enough?

**Comment by lucaspfsd** [comment]
Ok, I justs pointed out the Freegeoip since may exist users from a large company or public areas who are behind of one router(using NAT - 1 public IP).

Supose a company with 100 user, each one could do 10 request (navigate through 10 pages) at maximum per day (considering your lastest update).

**Comment by jackocnr** [comment]
Yer you raise a good point, but I'm nervous to switch to freegeoip, since lots of people are saying it's unreliable: http://stackoverflow.com/questions/20882227/is-there-another-site-like-freegeoip-net (lots of upvotes).

What do you think about the cookie stuff?

**Comment by lucaspfsd** [comment]
About the cookie stuff, I open a fork to do it. About freegeoip, I think that now it is ok, because the comments was on January 2014, and a guy teel that freegeoip received a DDoS attack, but ok, I understand you.

**Comment by jackocnr** [comment]
Yer I saw that, but then the next comment is "Seems to be down a lot lately" which was posted in June and has 10 upvotes.

BTW an easy workaround is for you to call freegeoip yourself and then initialise the plugin with defaultCountry set to the result.

Re: the fork, you probably just want to add to the condition on [this line](https://github.com/Bluefieldscom/intl-tel-input/blob/master/src/js/intlTelInput.js#L378) to something like this:

```js
// if they have not already loaded ipinfo on this page AND either they dont have the cookie plugin, or if they do: they haven't already set the cookie
if (!$.fn[pluginName].loadedAutoCountry && (!$.cookie || !$.cookie("intlTelInputLoadedAutoCountry"))) {
   $.fn[pluginName].loadedAutoCountry = true;
   if ($.cookie) {$.cookie("intlTelInputLoadedAutoCountry", true);}
```

**Comment by lucaspfsd** [comment]
Ok, I submitted today the pull request!

**Comment by jackocnr** [comment]
I don't see it.

**Comment by lucaspfsd** [comment]
Sorry, I've just edited the files, but not created the pull request. Now I did, follow the link: https://github.com/Bluefieldscom/intl-tel-input/pull/175

**Comment by jackocnr** [comment]
Thanks for submitting that. After thinking about it some more, there a other issues we need to address. 

Firstly, just looking at my current `loadedAutoCountry` solution: it only works for instances initialised at the same time - if you initialise the plugin a second time on the same page, it will hit ipinfo again, which is silly. Instead we should store the loaded country in that variable for future use. BUT then if we wait until the load has finished to set that variable, then every instance of that initialisation will hit ipinfo individually, so we need a separate `loadingAutoCountry` var, which is set to true straight away.

I will code this up over the weekend, and include your changes. Thanks for you input.

For my own notes: change cookie name to intlTelInputAutoCountry. Also don't call autoCountryDeferred.resolve() until that instance has it's own auto country.

Can I ask why you went for a cookie expiry of only 1 day?

**Comment by lucaspfsd** [comment]
About cookie value, I put on cookie the country code, e.g. 'BR'.
About cookie expiration, I put one day, because of client request over public ip, just because of it.

**Comment by jackocnr** [comment]
Ok I added this in v5.8.0 - let me know what you think

**Comment by armyofda12mnkeys** [comment]
Why not add an option to save the dropdown value chosen by the user in a cookie, even if not using 
'auto'? like we aren;t using auto but set a defaultCountry but if the user switches the language to another country, then it would be nice to store that as the default the next time the plugin is encountered. Since we have a 'Contact Info' form, then a 'Confirm your Contact Info' form in our questionnaire app, when the 2nd screen comes up, it goes back to the default preferred country we set and not the user's override (I think I'm going to manually code an onblur on that textfield that pulls the currently selected 'dropdown' value, and then sets a cookie value for now. and then sets the defaultCountry manually through that cookie [otherwise use the questionnaire's default country]).

**Comment by jackocnr** [comment]
I'm not sure about this because sometimes people just click around randomly to try things out. The only way we know they have actually selected their real country is if they go on to enter their phone number and submit the form. In this case, you have their country information anyway (if you use `getNumber` you get the full international number), and so when you pre-populate any future forms, the plugin will automatically select that country anyway. Do you see what I mean?
