### ISSUE TITLE
Different international calling formats

### ISSUE THREAD

**Issue by jmail22** [Bluefieldscom/intl-tel-input#186]
Hi

I would like to ask for additional change in this wonderful solution. 

Here is my proposal:

Let's say I am from USA. For me it is natural to input international phone number in format 011 48 600 000 000 (for Poland let's say)

When I am from Europe it might be natural to input 0048 600 000 000

Japan: 010 48 600 000 000

and so on. 

Most of them are described here - http://en.wikipedia.org/wiki/List_of_international_call_prefixes

Would it be possible to provide 1 of 2 functionalities:

1. replace international call prefix with +
or
2. recognize international call prefix and treat same as +

Right now one two of most popular international call prefixes - 00 and 011 are not recognize. 

Thanks in advance

Jarek

**Comment by jackocnr** [comment]
Hi there. First of all, can I assume you have nationalMode enabled (it is by default)? Because if not, then there is always a plus at the beginning of the input - you can't get rid of it, so this would all be moot.

Did you know that what you're describing currently works if you select the country from the list first? If you select UK then type "0044..." it will format the number correctly, and `getNumber` will work correctly, outputting "+44...".

But are you suggesting that it should automatically update the flag as you type it? If you have nationalMode enabled, then it's not possible because some of those prefixes you listed would clash with national UK numbers (which start "01"). I also think it's very likely that it wouldn't work even if you have nationalMode disabled considering there's so many different prefixes listed in that Wikipedia article you linked.

**Comment by jmail22** [comment]
well basically my first idea was to at least replace ^00 with + but that is quite easy and I have achived that by simply adding event on keyup to the field.

Then I thought it might be helpful to have such global solution ;)

During last 2 years I am working for telephony company and I know that if you put + at the begining half of people won't understand it and will do +0044 - that is reality. 

Basically I love your solution - it works when I need it to work (except on hybrid mobile app on Android :P). But your solution got one problem - it is not idiot proven :) When I get a country from IP in national mode this should guide me and change 011 to + when I am in States, 010 when I am in Japan etc. 


RIght now it respects 00 but doesn't respect 011 in US 010 in Japan nor 0011 in Australia - and I am talking about huge amount of people iving in these countries ;)

J

**Comment by jackocnr** [comment]
What do you mean "When I get a country from IP"?

As for changing 011 to + when the user is in the States - I don't think we should do this. Surely let the user type what they want to type - why change what they see? We can standardise it when we save it, but there's no need to confuse the user.

**Comment by jmail22** [comment]
I mean when I turn on ipinfo

you got right with standarise - is it working like that right now? When US and I would convert into E164 from number 01148600000000 I will get +48... ?


And what about Android hybrid app? do you have any idea why it might not work?

**Comment by jackocnr** [comment]
Yes E164 works as expected for your example. We use libphonenumber for this stuff, and you can test stuff on [this demo](http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html) - enter your number (excluding formatting chars) in the top, and "us" in the 2nd input and submit - you can see "AsYouTypeFormatter" outputs how we will format the number in the input, and "E164 format" shows what you will get when you call `getNumer` on the plugin.

Please open a separate issue for your hybrid app problem explaining your problem in more detail.

**Comment by jackocnr** [comment]
So can I close this issue? Or do you still think we need to change something?

**Comment by jmail22** [comment]
I think you can close it - I understand it can't personalised more for only us

**Comment by FesterCluck** [comment]
@jmail22 Another thing to note: Not all countries have only 1 exit code. Also, those that have multiple exit codes aren't always delineated by geographic location. Brazil delineates 4 exits codes by provider, so providing reasonable automatic exit code resolution across all countries is impossible. This is why the + format is used internationally, especially as mobile systems can automatically add the required exit code when + is dialed.
