### ISSUE TITLE
Need static use of library - from international to national numbers without putting the number to th input field

### ISSUE THREAD

**Issue by Doc999tor** [Bluefieldscom/intl-tel-input#188]
I've initialized the library and have the input works fine.
Also I get from the server numbers and of course want to perform the number and print it to the info panel in national apperance.
Any way doing it? 
Thanks 
Victor

**Comment by jackocnr** [comment]
If you load the utils.js file, you have access to all of the formatting methods etc. Details [here](https://github.com/Bluefieldscom/intl-tel-input/wiki/utils.js). Let me know if you have any other questions.

**Comment by Doc999tor** [comment]
Hi, Jack
It helped me a lot!
Can I find codeCountry by international code?
All utils function use countryCode for formatting
Thank you!
Victor

**Comment by jackocnr** [comment]
For `countryCode` you can just pass `null` if the `number` argument is a full international number.
