### ISSUE TITLE
Compatibility with X-Editable

### ISSUE THREAD

**Issue by three3211** [Bluefieldscom/intl-tel-input#192]
I am currently using the following plugin on my website: http://vitalets.github.io/x-editable/

I also use your wonderful plugin when a user registers on my website. However, when a user is editing their profile after they have signed up, I use the plugin above known as X-Editable. When I try initializing your plugin with an input that also is initialized with X-Editable, it seems to cause your plugin to malfunction and not work properly. I was wondering if you knew if the two plugins were compatible with each other? If so, please let me know how to use them together :+1: And If not, are there any plans to make the compatible with each other?

Thanks!

**Comment by jackocnr** [comment]
Hi there, I'm afraid I haven't come across that plugin before, and certainly don't have the time to debug integrations like this. Most likely this will be a case of getting x-editable to add support for this plugin e.g. supporting an input element with a wrapper div. But if you figure out that there is a bug with this plugin that is causing the problem then feel free to open another issue. Cheers.

**Comment by revolutionaries** [comment]
I worked up a plugin for x-editable that's working ok for me:

https://gist.github.com/revolutionaries/1f16579566dc782f2d4948050d3e4fe7
