### ISSUE TITLE
Provide ipinfo configuration

### ISSUE THREAD

**Issue by lorensr** [Bluefieldscom/intl-tel-input#193]
I'm having the issue mentioned in #130 with version `5.8.3`. I get a 401 error in the console, and when I open the URL:

https://ipinfo.io/?callback=jQuery21304393142939079553_1427624932964&_=1427624932965

it says:

SSL access is restricted to paid plans. See http://ipinfo.io/pricing for more details, or contact us via http://ipinfo.io/contact

It would be great if you could:

1) Default to http
2) Give a way to configure https if you have a paid plan (I assume there's an API key or something)

**Comment by jackocnr** [comment]
I don't specify the protocol (HTTP/HTTPS) in the ipinfo call, so it will be the same as whatever the page is using. You say you want it to default to HTTP, but if your page is HTTPS then all calls should be HTTPS as well.

See `ipinfoToken` option to pass a token if you have a paid plan.

Does that solve your problem?

**Comment by lorensr** [comment]
Thanks for the token option, sorry I missed it.

My site is https but I'd like to call ipinfo via http

**Comment by jackocnr** [comment]
You shouldn't be making HTTP calls from a HTTPS page - the browser will throw up a warning or something. If you don't want the page to be secure, then why are you using HTTPS?

**Comment by lorensr** [comment]
You could want the rest of the page secure, and not care about just that one call, but I'll just sign up for a plan, thanks again
