### ISSUE TITLE
Zimbabwe flag is selected if initial value is cleared

### ISSUE THREAD

**Issue by AGWA** [Bluefieldscom/intl-tel-input#196]
If the input has an initial value, and you clear it (e.g. by selecting the text and pressing the delete key), the Zimbabwe flag is selected instead of it remaining on the current flag.

I've put together a test case here:  https://www.cloudmutt.com/intl-tel-input-bug/

I have a possible fix and will submit a pull request shortly.

**Comment by jackocnr** [comment]
Thanks for reporting this. Fixed in v5.8.6.
