### ISSUE TITLE
Extension removed upon country change.

### ISSUE THREAD

**Issue by mtrejo** [Bluefieldscom/intl-tel-input#198]
v5.8.4
When the phone number contains an extension, if one selects another country using the dropdown then the extension is removed, for example:
Before: US +1 666-767-5432 ext. 123
After:    MX +52 666 767 5432 ext. 

I think adding this to utils.js#formatNumber:115 fixes the issue: `if (addSuffix && !val.split(extSuffix)[1]) {`

**Comment by jackocnr** [comment]
Thanks for reporting this, and you were right about the fix! Fixed in v5.8.7.
