### ISSUE TITLE
Feature request: exclusion list

### ISSUE THREAD

**Issue by Ghostavio** [Bluefieldscom/intl-tel-input#200]
Hello, this is an amazing plugin, and I saw you already have `onlyCountries` option. It would be also nice to have something like a `excludeCountries` option to do the opposite, setting which countries we don't want to show.

Thanks.

**Comment by jackocnr** [comment]
Interesting suggestion. Can you tell me your use case?

**Comment by Ghostavio** [comment]
Most countries in GCC (The Cooperation Council for the Arab States of the Gulf) exclude Israel from the phone list as they are not allowed to enter the country, so the only way for me to achieve this behaviour is either using `onlyCountries` and specifying every single country except Israel, or by hiding it with css (which is what I'm doing it right now).

**Comment by jackocnr** [comment]
Ok sounds like lots of people would find this useful. I'm on board. Unfortunately I don't have time to implement this right now, but I'm open to pull requests.

**Comment by Ghostavio** [comment]
Gonna do it this weekend :)

**Comment by jackocnr** [comment]
Hi @Ghostavio, this subject just came up in another issue. Any progress on this?

**Comment by caseyjhol** [comment]
I rigged this up really quick - it's the same code used for `onlyCountries` except I used `if ($.inArray(allCountries[i].iso2, this.options.excludeCountries) == -1) {`.

```javascript
var i;
// process onlyCountries option
if (this.options.onlyCountries.length) {
    // standardise case
    for (i = 0; i < this.options.onlyCountries.length; i++) {
        this.options.onlyCountries[i] = this.options.onlyCountries[i].toLowerCase();
    }
    // build instance country array
    this.countries = [];
    for (i = 0; i < allCountries.length; i++) {
        if ($.inArray(allCountries[i].iso2, this.options.onlyCountries) != -1) {
            this.countries.push(allCountries[i]);
        }
    }
} else if (this.options.excludeCountries.length) {
    // standardise case
    for (i = 0; i < this.options.excludeCountries.length; i++) {
        this.options.excludeCountries[i] = this.options.excludeCountries[i].toLowerCase();
    }
    // build instance country array
    this.countries = [];
    for (i = 0; i < allCountries.length; i++) {
        if ($.inArray(allCountries[i].iso2, this.options.excludeCountries) == -1) {
            this.countries.push(allCountries[i]);
        }
    }
} else {
    this.countries = allCountries;
}
```

http://embed.plnkr.co/oSUgB3PBQBeg4nH2wo8U/preview

**Comment by jackocnr** [comment]
Thanks for posting that @caseyjhol - it looks like it would work, but I really don't like all that duplication - instead I think we should pull that code out into a new function e.g. processCountries, into which we pass 2 arguments: A) the country array (either onlyCountries or excludeCountries), and B) a function which returns true or false depending on the result of the $.inArray call. So the call might look something like this:

```js
if (this.options.onlyCountries.length) {
   this.processCountries(this.options.onlyCountries, function(inArray) {
      return (inArray != -1);
   });
} else ...
```

**Comment by caseyjhol** [comment]
Good idea. I'll be gone the rest of the week, but I can submit a pull request next week unless you get around to it before me.

**Comment by jackocnr** [comment]
Added in v6.4.0
