### ISSUE TITLE
tel tag for enabling numeric keypad in mobile

### ISSUE THREAD

**Issue by srisowmya** [Bluefieldscom/intl-tel-input#202]
In the user's profile when they click on mobile field to enter the mobile number, then numeric keypad should be displayed instead of text. 
When I use tel tag as input type in the form to enable the numeric keypad in the mobile, It is not working.
Can anyone please help me with this issue

**Comment by jackocnr** [comment]
Hi there, I'm sorry you're having a problem, but this is not related to the plugin, so I'm going to close this. FYI if I visit the [demo page](http://jackocnr.com/intl-tel-input.html) on my Android phone, and click the input, I do get the numeric keypad.
