### ISSUE TITLE
Mobile View...

### ISSUE THREAD

**Issue by chimeramedia** [Bluefieldscom/intl-tel-input#208]
Hey,
This jQuery plugin is amazing!
I have one problem left to deal with now in my implementation.
When viewed on any modern mobile device the flag is simple tiny!

http://static.chmtk.co.uk/hosted/dev/mobile-layout.html

Take a look here. Is there any easy way to make the flags bigger easily? I've been playing around with the CSS and the flag PNG here but can't seem to make it work?
Keep up the good work
Many Thanks

**Comment by jackocnr** [comment]
Do you have the same issue with the [demo page](http://jackocnr.com/intl-tel-input.html) on mobile?

**Comment by chimeramedia** [comment]
No seems OK on your demo page. Must be something wrong with my CSS?
Thanks
