### ISSUE TITLE
isValidNumber --  "required" attribute is not honored

### ISSUE THREAD

**Issue by LiamK** [Bluefieldscom/intl-tel-input#209]
I have a phone field that I am using via angular, as shown below.

This phone field is *not* required.  However, form validation fails because the telInput.val() function returns "+1"  (in the case of a US country) when nothing has been entered in the field.  Subsequently, the isValidNumber() function checks the validity with intlTelInputUtils.isValidNumber() and that is not a valid number, so validation fails.

Somewhere here shouldn't it be checking to see if the input field is required or not?
If the field is not required, and if nothing has been entered (discounting the "+1" country code) then the field should be valid. 
What I expect is that the field should be not required unless I add the "required" attribute.

Help, please!  If there is some workaround for this, or a suggested patch, I would love to find out.

```
<input international-phone-number
                               preferred-countries="us"
                               default-country="us"
                               national-mode="false"
                               utils-script="/static/bower_components/intl-tel-input/lib/libphonenumber/build/utils.js"
                               responsive-dropdown="true"
                               class="form-control"
                               type="phone"
                               id="phone"
                               name="phone"
                               type="tel"
                               ng-required="false"
                               ng-model="main.contactFormParams.contact_phone"
                                />
```

**Comment by jackocnr** [comment]
What exactly do you mean by the "telInput.val() function"? If you're talking about the jQuery `val` function, then it should return an empty string if the input is empty! If you go to the [demo page](http://jackocnr.com/intl-tel-input.html) and run this in the JS console then it will return empty string: `$("#mobile-number").val()`.

**Comment by craigcampbell** [comment]
I'm having the same issue. It returns the '+' in the number before the area code?

**Comment by jackocnr** [comment]
@LiamK I see you are setting `nationalMode` to false. In this case, `autoHideDialCode` is enabled by default, which means if you focus the input when it's empty, it will auto insert the dial code (and if you blur it again it will remove it again). So if you focus and then submit, the value will be "+1". If you don't want this behaviour, you can set `autoHideDialCode` to false. Personally, I would recommend leaving `nationalMode` set to true so your users don't have to deal with country dial codes at all...

@craigcampbell I don't understand your problem. Can you describe your issue in more detail? Give me steps to reproduce, and tell me what you expect to happen and what is actually happening.

**Comment by LiamK** [comment]
I got a response from the author of the angular package https://github.com/mareczek/international-phone-number, and he made some changes that changed the behavior, but it's still not working quite right.  So, I don't think the issue I was having was with intl-tel-input, after all.

I really liked the nationalMode feature!  However, I couldn't get that working correctly.
Here is the issue, which someone else was having, as well.
https://github.com/mareczek/international-phone-number/issues/10
and
https://github.com/mareczek/international-phone-number/issues/24

I suspect this is also an issue in that package, however thanks for your response.

**Comment by craigcampbell** [comment]
@jackocnr My issue is I'm using most of the default settings and plugged it into my form. We're validating both client side and server side (spring) but for some reason it's still posting the '+' before the number. Now I have national mode set to false. My issue might be unrelated to spring capturing the '+', even when I val() the input field it returns just the int  I will probably have to fork and then change the JS from '+' to 0 I guess for a quick fix.  Thank you though.

**Comment by jackocnr** [comment]
@LiamK ok I don't know anything about angular so I'm afraid I can't help there.

@craigcampbell that sounds like a separate problem - please create another issue for that if you'd like me to look into it further.
