### ISSUE TITLE
Position issues, shifting on jquery validation

### ISSUE THREAD

**Issue by adgfx** [Bluefieldscom/intl-tel-input#212]
Hi,
I have a custom validation error messages displayed on my form. And when i click the submit button. The IntlTelinput's flag icon and dropdown caret shifts down. See this screenshot.
![issue](https://cloud.githubusercontent.com/assets/6965294/7230744/d77afaa4-e781-11e4-9949-35a8db2afa46.jpg)
What might be the issue, i have done a lot of research already :-(
It never resets or comes back to its actual position, i have to do a refresh. And it doesn't happen when the fields have values in it.

**Comment by jackocnr** [comment]
Did you see the Troubleshooting section about error messages in the readme? Does that help?

**Comment by adgfx** [comment]
Oh yes!! I did those changes and now the shifting issue is resolved, but the error element goes bit up. See attached!
![issue](https://cloud.githubusercontent.com/assets/6965294/7269148/fbba3496-e8e1-11e4-868e-42bc358aa0ff.jpg)

**Comment by jackocnr** [comment]
If the input container added by the plugin has the wrong position settings, you might need to add another container or something, but it's impossible to tell without seeing the code. TBH this is outside of the scope of the plugin - it's a general CSS question - perhaps you could try posting a question on stackoverflow.
