### ISSUE TITLE
Parent overflow hidden

### ISSUE THREAD

**Issue by drtzack** [Bluefieldscom/intl-tel-input#215]
My framework is using overflow:hidden and that blocks to see countrylist popup.

Is there any way to solve it?

**Comment by jackocnr** [comment]
I'm assuming you mean you're using this plugin within a container that has overflow:hidden? The only workaround would be to add padding-bottom or margin-bottom to the container so there's enough space for the dropdown.

**Comment by tripflex** [comment]
I'm having this issue as well, but what I think would be the best option is to somehow have the dropdown open upwards instead of down when this is the situation (rather than adding padding or margin) ... thoughts?

**Comment by tripflex** [comment]
So I found if you add to the `<ul>` the CSS `bottom: 100%;` it will cause dropdown to go upwards, would just need to do more research to see best way to handle it.

Here's some discussion from Chosen regarding this:
https://github.com/harvesthq/chosen/issues/86

**Comment by Drazzing** [comment]
Hi 

I have had to use the following jquery to cater for the my parent elements having overflow:hidden set. 

            var parent = this.$inputBox.parent();
                var offset = parent.offset();
                var dd_top = offset.top + parent.outerHeight();
                var dd_width = parent.width();
                this.$inputBox.parent('.intl-tel-input').find('ul').css({
                    "top": dd_top + "px",
                    "left": offset.left,
                    "position": "fixed",
                    "max-height": "200px"
                });

**Comment by jackocnr** [comment]
There's an active issue about this: https://github.com/Bluefieldscom/intl-tel-input/issues/246
