### ISSUE TITLE
Bootstrap label formatting

### ISSUE THREAD

**Issue by chrisvdb** [Bluefieldscom/intl-tel-input#220]
Thank you for this extremely useful plugin.

Everything works great except for the formatting of the input label in bootstrap. Whatever I try to do the label appears on the same line as the phone input field instead of above the input field as I'd like it to be. I was hoping that you might have an idea on how to fix this.

Relevant part of my code (in Jade format):

    form(data-toggle='validator', role='form')
      .form-group
        label.control-label(for='familyName') Family name
        input#familyName.form-control(type='text', data-error='...', placeholder='...', required='')
        .help-block.with-errors
      .form-group
        label.control-label(for='phoneNumber') Phone number
        input#phoneNumber.form-control(type="tel", placeholder="")
        input#parsedPhoneNumber.hide(name='parsedPhoneNumber', type='text', required='')
        input#isValidPhoneNumber.hide(name='isValidPhoneNumber', pattern='^true$', type='text', data-error='...', required='')
        .help-block.with-errors

The result is:

Family name
[input field]
Phone number [input field]

The additional code is for validation purposes. Removing it does not impact formatting/positioning.

**Comment by jackocnr** [comment]
I'm afraid I'm not familiar with Jade. Can you please setup a Codepen to show the problem? You can fork [this codepen](http://codepen.io/jackocnr/pen/pvdgrO) which already has the plugin and Bootstrap included.

**Comment by chrisvdb** [comment]
Thanks for the pointer... got it working by adding .intl-tel-input to the CSS (although I don't know exactly why that does the trick).

http://codepen.io/anon/pen/GJpwpy

**Comment by jackocnr** [comment]
Cool. `display: table-cell` is a very specific one. `display: block` is the more common one, but whatever works ;)

**Comment by callshark** [comment]
For anyone else who runs into this, the CSS to get it working in the current version is:

```
.iti {
  display: block;
}
```

**Comment by aadarsh977** [comment]
It works for me in 17.0.12 with:

<pre>
.iti {
    display: block!important;  
}  
</pre>
