### ISSUE TITLE
not adding country code

### ISSUE THREAD

**Issue by mqct** [Bluefieldscom/intl-tel-input#223]
for some reason this is not adding the  country code when selecting the country flag. None of the demos work when downloaded either....

**Comment by jackocnr** [comment]
That's strange, does it work on [the demo page](http://jackocnr.com/intl-tel-input.html)?

Can you setup a Codepen to show the problem?

**Comment by mqct** [comment]
the demo page only shows the placeholder, it doesn't populate the field with the country code

**Comment by jackocnr** [comment]
See the `nationalMode` option, enabled by default.
