### ISSUE TITLE
Can't get the automatic country's data

### ISSUE THREAD

**Issue by Rainier9** [Bluefieldscom/intl-tel-input#227]
Hi, I'm in need of populating some select-option elements as soon as I get the country of the user. Is there any way I could access the data of the country, even before the user inputs his number?

For example:
1. User in Brazil goes to the site
2. Input gets the Brazilian flag (because of the auto property)
3. Get the current country's data in this moment.

**Comment by jackocnr** [comment]
You just need to use the `.done()` method e.g.

```js
$("input").intlTelInput({
    defaultCountry: "auto"
}).done(myCallback);
```

**Comment by jackocnr** [comment]
Actually I will leave this issue open until I (or someone else) finds the time to update the readme with this information, probably just under the `defaultCountry` option.
