### ISSUE TITLE
Austrian Tel # - Automatically adds zero to the beginning when not needed

### ISSUE THREAD

**Issue by bhahn1800** [Bluefieldscom/intl-tel-input#228]
When we render the text '+43676800505017' (+43 Austrian area code) in the 'tel' input field and run the following:

		    this.$el.find("#number").intlTelInput({
                          utilsScript: "libs/intltelinput/utils.js"
		    });

The correct country field is auto-selected for Austria, but the main text field shows '0676 800505017' where there is an extra zero placed at the beginning before the six.  We have some users who could be confused by this.

**Comment by jackocnr** [comment]
If you leave `nationalMode` set to true (which it is by default), then we use Google's [libphonenumber](https://github.com/googlei18n/libphonenumber) to convert international numbers into national numbers. You can see how that lib processes numbers by submitting your example international number into [this demo](http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html) - you can see that the "national format" adds that leading 0. If you think this is incorrect, please raise the issue with them.
