### ISSUE TITLE
Is custom geoIpLookup function working?

### ISSUE THREAD

**Issue by felipe-pereira** [Bluefieldscom/intl-tel-input#230]
Hi, I'm trying to use a custom geoIpLookup function (as described in the code sample), but the default behavior is always firing (it makes a request to ipinfo.io, then sets the country correctly).

Can you see something wrong here (or check if that is working on your side)? Thanks

```javascript
var options = {
  autoFormat: true,
  autoHideDialCode: true,
  defaultCountry: 'auto',
  nationalMode: false,
  numberType: '',
  onlyCountries: void 0,
  preferredCountries: ['ca', 'us', 'ca'],
  responsiveDropdown: false,
  geoIpLookup: function(cb) {
	console.log('never called :( ');
	$http.get('//freegeoip.net/json')
	.success(function(results) {
	  if (results && JSON.parse(results).country_code) {
		cb(JSON.parse(results).country_code.toLowerCase());
	  } else {
		cb('ca');
	  }
	})
	.error(function(error) {
	  cb('ca');
	});
  },
  utilsScript: ''
};

$('#new_phone').intlTelInput(options);
```

**Comment by jackocnr** [comment]
Are you sure you're using v6.0.0?

Does this example work for you? http://codepen.io/jackocnr/pen/eNWzXE?editors=001

**Comment by felipe-pereira** [comment]
That was the problem, was using an older version) where this particular bits weren't working, thanks
