### ISSUE TITLE
.getValidationError returns "TOO LONG" on too short number

### ISSUE THREAD

**Issue by jmoponfire** [Bluefieldscom/intl-tel-input#232]
Not sure if this is a bug. 

When I call getValidationError on number: 
7758880 with United States flag, 
isValidNumber returns false (which it should). 
But the getValidationError returns 3, or "TOO LONG"

Shouldn't it return TOO SHORT?

**Comment by jackocnr** [comment]
This is a [known issue](https://github.com/googlei18n/libphonenumber/issues/358) with libphonenumber.
