### ISSUE TITLE
getNumber blank right after initialization

### ISSUE THREAD

**Issue by Azaret** [Bluefieldscom/intl-tel-input#240]
Hi,

I would like to get the phone number formatted after intl-tel-input initialize, but it return blank.

ie:
```javascript
$(this).intlTelInput({
  defaultCountry: "fr",
  utilsScript: "/Web/Scripts/Libraries/libphonenumber.js",
  numberType: "FIXED_LINE"
});
$(this).intlTelInput("getNumber", 1);
```

I've read #160 and #153, because I guess it's due to the loading of `libphonenumber`, I'm missing some callback or event to know when the input is ready, unless I missed something.

**Comment by Azaret** [comment]
One workaround this issue is to load `libphonenumber` like any other scripts in the DOM rather than using `utilsScript`.
Is there a down side of doing this ?

I doesn't look like there is anything linked directly to the loading of `libphonenumber` in your code, but I'm not sure.

**Comment by jackocnr** [comment]
You need to put your code in a `done()` callback - see https://github.com/Bluefieldscom/intl-tel-input/issues/227
