### ISSUE TITLE
Use phone format without trailing zeros

### ISSUE THREAD

**Issue by karolrybak** [Bluefieldscom/intl-tel-input#241]
Hi, is it possible to use international format for phone numbers so eg. UK number would be 7400 123456 instead of 07400 123456 as it is now ?

**Comment by jackocnr** [comment]
You can use international format by setting `nationalMode` to false.

**Comment by karolrybak** [comment]
Well this is partial solution, as there is unnecessary country prefix now visible. It would be great to have an option that allows me to use nationalMode but with international phone formats. Until then I guess I'll have to get back to good old code hacks :)

**Comment by jackocnr** [comment]
The number format you are proposing is not a valid format - I don't think it's a good idea to ask users to enter an invalid number!

**Comment by karolrybak** [comment]
Well as all the numbers we use in the application are all in international format it seems to be valid. For now client agreed on using nationalMode=false. So it's ok. Thanks for your amazing work :)
