### ISSUE TITLE
Load utils.js, when all plugins are bundled.

### ISSUE THREAD

**Issue by le0nik** [Bluefieldscom/intl-tel-input#242]
How do i do it? I install intl-tel-input with npm and require it in my app. All plugins are bundled into one file for production. How am i supposed to load utils.js, if int-tel-input only accepts it's path instead of letting me require it myself?

**Comment by jackocnr** [comment]
It will work if you just include it in your main production file, but the reason we don't recommend this is because it's pretty big, so it's better to load it asynchronously when your page has finished loading (which is what the `utilsScript` option does).
