### ISSUE TITLE
Disabled input on mobile still shows country select list

### ISSUE THREAD

**Issue by karolrybak** [Bluefieldscom/intl-tel-input#243]
As in description, this works perfectly on desktop browsers, but on mobile it is still possible to change current country when control is set to disabled.

**Comment by jackocnr** [comment]
Thanks for reporting this - it's part of a bigger change outlined here: https://github.com/Bluefieldscom/intl-tel-input/issues/244

Unfortunately I wont have time to work on this any time soon, but I'm open to pull requests!
