### ISSUE TITLE
Display the country list on top of everything

### ISSUE THREAD

**Issue by seroche** [Bluefieldscom/intl-tel-input#246]
Hi,

First I want to thank you for the great quality of your work. Your lib is easy to use and very user friendly. 

However, i have one small problem:

![image](https://cloud.githubusercontent.com/assets/12636347/8297920/8f10b73c-1994-11e5-9109-b4263380b4b5.png)

As you can see the country list is displayed within my div and not on top of everything. 
> Is there a way to do that so the user can see the full list without having to scroll down?

Browser: IE11 (IE8 compatibility mode due to Sharepoint 2010....)

Thank you,
Seb

**Comment by caseyjhol** [comment]
This would probably need to be resolved by adding a `container` option and setting it to `'body'` similar to Bootstrap popover (http://getbootstrap.com/javascript/#popovers-options). I implemented the same feature in Bootstrap-Select and am in the process of working on a pull request for this right now.

**Comment by jackocnr** [comment]
Hi guys. @caseyjhol I'm interested to see what you come up with in your pull request, but as far as I can see this is just a simple CSS issue relating to `z-index` and `overflow` and is outside of the scope of the plugin, because it depends on how you use these CSS rules on the other elements on the page.

**Comment by caseyjhol** [comment]
If you have the phone input inside a div with `overflow: scroll` or `overflow: hidden`, currently it is impossible for the intl-tel-input dropdown to ever appear outside the div. See http://silviomoreto.github.io/bootstrap-select/#container for an example of the problem/fix.

**Comment by jackocnr** [comment]
Hmm interesting. Your code may also be useful for this mobile dropdown issue: https://github.com/Bluefieldscom/intl-tel-input/issues/244 where we plan to move back to a custom dropdown, but would need it to be full-screen, which would mean injecting it at the end of the body.

**Comment by caseyjhol** [comment]
Definitely - I'm still familiarizing myself with your code, but I should be able to get a pull request/working demo within a few days.

**Comment by caseyjhol** [comment]
I'll need to clean up the code a bit before the pull request, but check out: http://embed.plnkr.co/lobCJwstCUnRHx5FxZ9s/preview.

A total of about 33 new lines of JS and a few new lines of CSS. This could be easily adapted to a "full screen" implementation to resolve #244.

**Comment by jackocnr** [comment]
Excellent work! Thank you. I look forward to seeing the code.

**Comment by caseyjhol** [comment]
I'm running into issues with ImageMagick when running `grunt build` on Windows 8. But you can check out the code at https://github.com/caseyjhol/intl-tel-input. I'm setting up a Linux VM to hopefully avoid issues with building in the future and can have it ready tomorrow.

**Comment by jackocnr** [comment]
`grunt build` does a lot of crazy stuff with the flag images, but you don't need to do that. Just run `grunt sass` when you need to build the CSS and `grunt js` when you need to build the JS.

**Comment by caseyjhol** [comment]
@jackocnr This can be closed.

**Comment by jackocnr** [comment]
See `dropdownContainer` option.
