### ISSUE TITLE
International Detection

### ISSUE THREAD

**Issue by MatthewBaldock** [Bluefieldscom/intl-tel-input#250]
Seems to work great from going between Canada and U.S. but doesn't like to go from U.S. to any other country.

**Comment by jackocnr** [comment]
I'm sorry but I don't understand, are you talking about changing the flag using the dropdown? What do you mean when you say "International Detection"?

**Comment by MatthewBaldock** [comment]
Yes, the flag only switches between Canada/ U.S. but even with all the settings I tried, (I.P. detection or regular auto detect etc...) It won't format to other country numbers without manually switching.

**Comment by jackocnr** [comment]
I can't test using defaultCountry "auto" with other countries as I'm in the US. But if I set defaultCountry to "gb" (United Kingdom), then type a number, it formats it correctly.

Can you please give exact steps to reproduce the problem? And what you expect to happen and what actually happens.

**Comment by MatthewBaldock** [comment]
I expect that when I type in a Hong Kong Number the flag to switch to Hong Kong no matter what flag is default. When its Canada to US it Seems fine but from any other country to Canada or to US or From Canada to China or US to China is just doesn't do anything.

**Comment by jackocnr** [comment]
I'm guessing you're typing national numbers? It's impossible for the plugin to know which country the number is for if you don't include the international dial code (e.g. +44 for the united kingdom).

**Comment by MatthewBaldock** [comment]
Entering the international dial code doesn't change the flags either. The only thing that changes the flags to anything other than U.S or Canada is manually and for my purposes it needs to do it automatically based off the number that is in the input field which seems like something it's supposed to do but doesn't for me.

**Comment by jackocnr** [comment]
That's strange. Does it work for you on the [demo page](http://jackocnr.com/intl-tel-input.html)? If I go there and type +44 then I see the UK flag.

**Comment by MatthewBaldock** [comment]
Damn. It worked, thank you. I feel dumb but also relieved.
