### ISSUE TITLE
How to validate the  count of number  as per the country selected?

### ISSUE THREAD

**Issue by Dineshrajaa** [Bluefieldscom/intl-tel-input#251]
Hello ,
 I am using this plugin for making an app's login module and I am in need of validating the number of characters/numbers that I have to enter and notify the user if he/she fails to enter the required count and I need to do this based on the country selected
Example:If the user selects India I have to validate the field whether it has got 10 numbers entered in it(Excluding the country code(+91))

Kindly help me to do this.
Regards,
Dinesh

**Comment by jackocnr** [comment]
See `isValidNumber` and `getValidationError` methods in the readme.

**Comment by Dineshrajaa** [comment]
Thank you jackocnr that was helpful :)
