### ISSUE TITLE
Only one country displayed in the countries list

### ISSUE THREAD

**Issue by seroche** [Bluefieldscom/intl-tel-input#255]
Hi all,

I'm experiencing a strange bug. 

I only see the default country in the countries list:

Example:
![image](https://cloud.githubusercontent.com/assets/12636347/8665988/2de05e74-2a1d-11e5-8280-c5958df7b6a0.png)

Here is the code i used to initialized the controls:
    $('#step-' + step_num + ' input.telBox') // Inits all the telephone inputs
        .intlTelInput({
            autoFormat: true,
            nationalMode: false,
            autoPlaceholder: false,
            allowExtensions: true,
            defaultCountry: "hk",
            preferredCountries: ["hk", "cn"],
            utilsScript: '/_layouts/HRDatabase.SPM.SpWebPart/Scripts/External/intlTelInput.utils.min.js'
        });

Extract from the CSS
.iti-flag {
    background-image: url("/_layouts/images/HRDatabase.SPM.SpWebPart/flags.png") !important;
}

I'm using the latest version of the library. 

Did i miss something obvious?

Thank you,
Sebastien

**Comment by thebrit** [comment]
Your utilsScript: method should be pointing to "utils.js"

**Comment by jackocnr** [comment]
I would guess that you have a CSS conflict that is affecting the dropdown. Do you have an JS errors?

I would need a jsfiddle/codepen to help further.

**Comment by seroche** [comment]
I fount the root cause. This was caused by a CSS style in charge of hiding li...
ul#position li {
    display: none;
}

I just replaced this style by:
ul#position > li {
    display: none;
}

My fault! 

Thank you,
Sebastien
