### ISSUE TITLE
Autocomplete option

### ISSUE THREAD

**Issue by ibarral** [Bluefieldscom/intl-tel-input#256]
Hello,

I'm trying to implement the "autocomplete" attributes to a form, and I just detected that it doesn't works if intl-tel-input is used.

It seems to be a problem with the autocomplete="off" attribute that intl-tel-input always inserts to the phone input field used with the plugin. I just tried setting that attribute to autocomplete="tel" using Dev Tools Inspector and it works ok.

I think that the best solution is to respect the autocomplete attribute that's used on the input field, and don't force it to be always "off".

More information about autocomplete attributes: 
https://developers.google.com/web/fundamentals/input/form/label-and-name-inputs

Examples (needs chrome 42+):
https://greenido.github.io/Product-Site-101/form-cc-example.html

Thanks!

**Comment by jackocnr** [comment]
Yes unfortunately the plugin is incompatible with the `autocomplete` attribute. From the comments in the source:

"// prevent autocomplete as there's no safe, cross-browser event we can react to, so it can easily put the plugin in an inconsistent state e.g. the wrong flag selected for the autocompleted number, which on submit could mean the wrong number is saved (esp in nationalMode)"

**Comment by julien-c** [comment]
Also see https://github.com/jackocnr/intl-tel-input/issues/587#issuecomment-300244833
