### ISSUE TITLE
Using 011 instead of + for international Number, Flag doesn't change

### ISSUE THREAD

**Issue by mytello01** [Bluefieldscom/intl-tel-input#257]
When i use your demo (http://jackocnr.com/intl-tel-input.html, USA is preselected) and i typ in +4917012345678 it changes the flag to German. 

But when i typ in 0114917012345678 which is basically the same it doesn't change the flag, is there a reason for that? Both is the same german number. (011 the exit code for USA)

Phonelib is detecting both ways of input http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by jackocnr** [comment]
That other format is not standardised - it varies depending on which country you are dialing from. See https://github.com/Bluefieldscom/intl-tel-input/pull/5
