### ISSUE TITLE
allCountries as a dependency?

### ISSUE THREAD

**Issue by exiadbq** [Bluefieldscom/intl-tel-input#266]
Thanks for the awesome input.

Any particular reason to have the areas removed? if priority, areaCodes  can be added.
*Removed: Åland Islands, Christmas Island, Cocos Islands, Guernsey, Isle of Man, Jersey, Kosovo, Mayotte, Pitcairn Islands, South Georgia, Svalbard, Western Sahara*

Alternatively, if allCountries can be injected, would that be better?

**Comment by jackocnr** [comment]
I think a lot of those are just regions of other countries. Are you saying you want to include them? Can I ask why?

**Comment by exiadbq** [comment]
Yes. For business, those areas are considered targeted areas. And were spotted missing by QA. 
I can see them supported in flags, even google formatting cannot differentiate between those areas, it would be good to have them.

**Comment by jackocnr** [comment]
Hmm I think this is a very specific use case. I don't want to add weight to the plugin unless it will be useful to most people. So for now, you can just use `getCountryData` before you initialise the plugin to modify (add to) the country data. See an example here: http://jackocnr.com/lib/intl-tel-input/examples/gen/modify-country-data.html

**Comment by jackocnr** [comment]
FYI most of those countries have now been re-added.
