### ISSUE TITLE
Use drop down as standalone field

### ISSUE THREAD

**Issue by PierceMcGeough** [Bluefieldscom/intl-tel-input#268]
Is it possible to use the dropdown to populate a standalone prefix field?

We want to have mobile_prefix and mobile_number in the database. This seems the best solution.

The problem we have with the plugin currently is that a user would enter 075xxxxx we would want to store this as +4475xxx for sending SMS but throughout the system we want to display the national number 075xxx. However if we have stored it as +4475xxx it returns as such to the edit input.

Would this feature be available or maybe it is already there and I missed it.

**Comment by jackocnr** [comment]
You cannot do this with the plugin. By default, the plugin encourages users to enter their national number, then if you use `getNumber`, by default you get the standardised international number to store on the backend. Then when you want to show the form again, if you initialise the plugin when the input has that value (or use `setNumber`) then by default it will convert it to the national number again for the user to see. Does that make sense?

**Comment by PierceMcGeough** [comment]
Hi,

Yes it makes sense thanks although I cannot seem to get it working. This is my example.

```
$('#phone_mobile_display').intlTelInput({
		nationalMode: true,
		preferredCountries: ['gb', 'ie'],
		utilsScript: "/assets/plugins/intl-tel-input/lib/utils.js"
	});
```

Add a UK number of 07547786810 and using getCleanNumber it becomes +447547786810

Then if I set the number `$('#phone_mobile_display').intlTelInput('setNumber', '+447547786810');` it still displays in the input/edit as +447547786810. If I under stand what you are saying I should be expecting 07547786810 to appear. Am I correct?

**Comment by PierceMcGeough** [comment]
I have also tried the following but get a console error `Uncaught ReferenceError: intlTelInputUtils is not defined`

```
$('#phone_mobile_display').intlTelInput('setNumber', '+447547786810', intlTelInputUtils.numberFormat.NATIONAL);
```

**Comment by PierceMcGeough** [comment]
Sorry I just realised I was using an outdated version. It was part of a theme that wasn't updated.
Thanks for your help.

**Comment by jackocnr** [comment]
intlTelInputUtils.formatNumberByType("+447547786810", "gb", intlTelInputUtils.numberFormat.NATIONAL)

**Comment by PierceMcGeough** [comment]
How is that instantiated?

I'm running it on a page that doesn't have the plugin running on it. I get an error 

`Uncaught TypeError: Cannot read property 'NATIONAL' of undefined`

I then remove the intlTelInputUtils.numberFormat.NATIONAL and replace it with 'NATIONAL' and I get the following error

`Uncaught TypeError: intlTelInputUtils.formatNumberByType is not a function`

This is the code I am trying to run. Also we will not know at this stage if the number is gb or ie etc etc

```
<script type="text/javascript" src="plugins/intl-tel-input/lib/utils.js"></script>

// inside doc ready
var number = '+447547786810';   // this will be a smarty variable from DB
var op_number = intlTelInputUtils.formatNumberByType(number, "gb", intlTelInputUtils.numberFormat.NATIONAL);

console.log(op_number);
```

**Comment by jackocnr** [comment]
As I said, you just need to load the utils.js script (from lib/libphonenumber/build/) onto the page (if you're not using the plugin, then just load it manually like a normal script) and then that line I posted should work. Please make sure you're using the latest version.
