### ISSUE TITLE
XMLHttpRequest Error

### ISSUE THREAD

**Issue by PierceMcGeough** [Bluefieldscom/intl-tel-input#269]
After downloading the plugin and running the demo file as is, without any changes I get an XMLHttpRequest error which stops formatting taking place. 

This is on the latest Chrome and Opera

**Comment by jackocnr** [comment]
Can you look in Chrome Dev Tools and see which request is causing that error? I'm guessing the utils script?

**Comment by PierceMcGeough** [comment]
Yes its the utils script. It appears to be a cross server issue. I was running all locally from files (no local server)
I don't if there is even a fix you can do for that.

**Comment by jackocnr** [comment]
We use jQuery's $.ajax to load the utils script, which requires a local server. I personally use npm's [http-server](https://www.npmjs.com/package/http-server).
