### ISSUE TITLE
placeholder value

### ISSUE THREAD

**Issue by asiminiceanu** [Bluefieldscom/intl-tel-input#27]
It could be great if for every country selected the placeholder value is changed so that a valid phone number example is presented to the user based on the selected country.

**Comment by riyajk** [comment]
> Currently we trigger a "change" event (on the input) when the user selects a flag from the dropdown, so can you just listen for that? There's an example here: http://jackocnr.com/lib/intl-tel-input/examples/gen/country-sync.html

Link is not working. :( Also, did any the solution provided  as @asiminiceanu  putted as a question?

**Comment by jackocnr** [comment]
I've updated the link. I'm sorry but I don't understand the rest of your question.

**Comment by riyajk** [comment]
@jackocnr I want to show phone number format  placeholder as per country changed.How should I do this?

**Comment by asiminiceanu** [comment]
@riyajk I will have a look at what I did 5 years a go and come back to you with an example.
