### ISSUE TITLE
typing intl dial code + phone number, then deleting intl dial code clears country selection

### ISSUE THREAD

**Issue by mrhota** [Bluefieldscom/intl-tel-input#273]
1. Enter +61 for Australia
2. Enter 0412341234 as phone number following international dialing code.
3. Delete +61 from beginning of input.
4. Observe that the flag is cleared and the phone number is invalid whereas typing 0412341234 results in a valid phone number when Australia has been selected.

You have to clear the input entirely to get the input back to a good state.

**Comment by jackocnr** [comment]
Yes I can reproduce, but the behaviour is working as designed.

So you're saying you fill the input with +610412341234 and then delete the +61 - what happens is: when you delete the 1, you leave a number starting +60, so the flag changes to Malaysia, then you delete the 6, so the number starts +0 which is an invalid country code, so it goes to invalid grey state, then you delete the + and it still doesn't have a valid country selection or a valid country code, so it doesn't know what to do.

If you want to deal in national numbers, then you have to select the flag manually.

Do you think we should handle this differently? Doesn't seem like a likely sequence of events to me.

**Comment by mrhota** [comment]
@jackocnr that makes perfect sense to me. I'll close this issue. Thanks for your help!
