### ISSUE TITLE
doesnt work inside a div.container but works outside it (refer screenshots)

### ISSUE THREAD

**Issue by rohil69** [Bluefieldscom/intl-tel-input#277]
I am using Bootstrap 3.3.4 to create a contact form and using intl-tel-input for the auto-tele country codes. However I found the module not working in my case which had lots of nested divs.
I then copy pasted the <input> tag  with the id specified with the function to various places on my page. I found that it work with the outer div and inner/ nested divs had problems displaying [check screenshots for better understanding of what i did] 
![code](https://cloud.githubusercontent.com/assets/3790213/9470865/8fa38270-4b6b-11e5-9855-09ba90a29848.JPG)
![preview](https://cloud.githubusercontent.com/assets/3790213/9470866/8fa7b494-4b6b-11e5-9251-b891951f518d.JPG)

**Comment by jackocnr** [comment]
It's impossible for me to help without the rest of the code (the initialisation code, and the CSS etc). Please can you create a codepen to replicate the problem.

**Comment by rohil69** [comment]
here is the link : http://codepen.io/rohil69/pen/KpOxEm/

**Comment by jackocnr** [comment]
The problem is just that you're using the same ID for multiple elements. See http://stackoverflow.com/questions/11114622/jquery-id-selector-works-only-for-the-first-element

**Comment by rohil69** [comment]
that was just to show you. (maybe, you didn't read my 1st comment, why i did it)
The multiple <input> is just for testing purpose since i wasn't getting the desired result in the form where I wanted. 
yes, you were right about the first element. But I had that ID ('#phone') attached to the <input> near the label "Contact" ONLY, initially.

EDIT: the issue has been resolved. I had multiple ID's declared with the same <input> tag. keeping only the one used for initialising this script worked. Thanks Jack! :) :+1:
