### ISSUE TITLE
Where +31 changes country flag, 0031 does not

### ISSUE THREAD

**Issue by Rvanlaak** [Bluefieldscom/intl-tel-input#279]
If another country than The Netherlands is selected, and the valid number `+31 6 12345678` is entered the country flag correctly changes to the Dutch flag (or any other country example).

Although, the number `0031 6 12345678` also is valid, and the international number output also is correct when we enter this number. Unfortunately, the flag does not change to Dutch. This flag can be changed to Dutch right?

http://jackocnr.com/lib/intl-tel-input/examples/gen/national-mode.html

**Comment by jackocnr** [comment]
Please search before posting - this question has been answered before.

**Comment by mytello01** [comment]
I also asked for that, I agree with you I think this is an important feature.

**Comment by jackocnr** [comment]
The "00" syntax is not equivalent to "+": see https://github.com/Bluefieldscom/intl-tel-input/pull/5
