### ISSUE TITLE
Unstyled country <select> list when in mobile view

### ISSUE THREAD

**Issue by mpiasta-ca** [Bluefieldscom/intl-tel-input#280]
Just updated our app's `intl-tel-input` version from the one we setup 8 months ago.

Found this new weird and undesirable behavior:

```
this.isMobile = /Android.+Mobile|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
```

Perhaps this should be a toggle-able option, but forcing this always as a default is undesirable. We were perfectly fine using the styled `<ul>` list which had flag icons. There was no issues with our users scrolling the list on a mobile device.

This `<select>` list doesn't even have consideration for our "preferredCountries".

**Comment by jackocnr** [comment]
Yer I intend to improve the experience on mobile: https://github.com/Bluefieldscom/intl-tel-input/issues/244

Unfortunately I don't currently have time, but I'm open to pull requests.
