### ISSUE TITLE
when choosing a country to insert in input 'national code'

### ISSUE THREAD

**Issue by dusblinov** [Bluefieldscom/intl-tel-input#282]
hello! when choosing a country, how can i to insert in input 'national code'  to the top of the phone? (not Placeholder)

**Comment by jackocnr** [comment]
I'm sorry but I don't understand your question.

**Comment by jackocnr** [comment]
If you're trying to get it to insert the country calling code into the input when you select a country from the dropdown, then you could try setting nationalMode: false.
