### ISSUE TITLE
onlyCountries allows countries not in list

### ISSUE THREAD

**Issue by faiz-shaikh** [Bluefieldscom/intl-tel-input#288]
Hi, when we use onlyCountries for e.g ceu and then enter a number (not from CEU) the input filed accepts the number without throwing an error or showing the flag. 
![image](https://cloud.githubusercontent.com/assets/6928381/9656239/bfe21e32-522e-11e5-93bb-32cd4efc60d7.png)
Should the input allow any other countries apart from the config ? Would this need an enhancement to prevent it from doing so ?

**Comment by jackocnr** [comment]
This is currently working as designed. I'm actually moving away from the idea of preventing the user from doing anything. I think this is an edge case which you should just handle when you do your form validation.
