### ISSUE TITLE
Two same country drop downs when 1 selection on onlyCountries

### ISSUE THREAD

**Issue by faiz-shaikh** [Bluefieldscom/intl-tel-input#289]
Hi,
Is there a way to prevent the same country being shown twice when we select just one country in 
onlyCountries.

![image](https://cloud.githubusercontent.com/assets/6928381/9656547/077659be-5231-11e5-91a7-a6e81b5cd491.png)

I assume it shows as preferredCountries, can this be turned off or changed to false.

**Comment by jackocnr** [comment]
Yes you can set preferredCountries to an empty array!
