### ISSUE TITLE
intl-country-input

### ISSUE THREAD

**Issue by nlwillia** [Bluefieldscom/intl-tel-input#291]
Adding `intl-tel-input` to a form that also solicits a country (ex: an address form with a phone number) raises the question of whether the country input can be styled in the same way as the phone field.  (The address country and phone country may not be the same, and there are a number of reasons why you might prefer or need to represent them separately.)  Doing this with a regular select isn't viable given limitations on what you can do with an option list.  But `intl-tel-input` already has 99% of what you would need to build just a country dropdown.

I created a parasite plugin that more-or-less accomplishes this, but it's a pretty big hack compared to implementing the feature relative to the widget's internals.  Is it too much scope creep to consider adding this kind of behavior to the core?  Ideally, I guess you'd have a base country plugin that the phone plugin would extend, but that would be a much more substantial change, and the two scenarios have a lot in common.

[demo](http://embed.plnkr.co/XdsAmFEyphZccm0xU8gv/preview)
```
(function($) {
	/** Hides original element and bootstraps a stripped-down intlTelInput proxy that behaves like a country-selector. */
	function intlCountryInput(orig, options) {
		orig.hide();
		
		var proxy = $('<input>').css('width', '100%').attr('tabindex', -1).insertAfter(orig).on('focus', function(e) { e.preventDefault(); });
		proxy.intlTelInput({
			autoFormat: false,
			autoPlaceholder: false,
			preferredCountries: options.preferredCountries,
			onlyCountries: options.onlyCountries
		});
		
		var root = proxy.closest('.intl-tel-input').addClass('intl-country-input');
		var dropdown = $('.flag-dropdown', root).css('width', '100%');
		var selected = $('.selected-flag', dropdown).css('width', '100%');
		var countries = $('.country-list', dropdown);
		$('.country', countries).on('click', function() { selected.focus(); });
		$('.dial-code', countries).hide();
		
		var countryToValue = typeof options.countryToValue === 'function' && options.countryToValue || function(country) { return country.iso2; };
		function proxyChanged() {
			var country = proxy.intlTelInput('getSelectedCountryData');
			proxy.val(country.name);
			orig.val(countryToValue(country));
		}
		
		var valueToCountryCode = typeof options.valueToCountryCode === 'function' && options.valueToCountryCode || function(value) { return value; };
		function origChanged() {
			proxy.intlTelInput('selectCountry', orig.val() && valueToCountryCode(orig.val()) || $('.country', dropdown).first().attr('data-country-code'));
			proxyChanged();
		}
		
		proxy.on('change', function() {
			proxyChanged();
			orig.trigger('change');
		});
		orig.on('change', function() {
			origChanged();
		});
		origChanged();
	}
	$.fn['intlCountryInput'] = function(options) {
		return $(this).each(function() {
			intlCountryInput($(this), options);
		});
	};
})(jQuery);
```

**Comment by jackocnr** [comment]
This is a cool hack. Would you be able to setup a codepen to show it working?

I'm doubtful about adding this functionality to the core, as it's completely outside the scope of the plugin. That said, if it's only a couple of lines I would maybe consider it. I don't have time to look into it myself, but if you want to you could dig into the code and have a think about how many changes would need to be made, and how many LOC it would add...

**Comment by nlwillia** [comment]
Here's a [codepen](http://codepen.io/nlwillia/pen/RWWYLo) version of the plunkr demo above.

I'll look at what core support would look like and submit a PR for you to evaluate if it seems reasonable.

**Comment by jackocnr** [comment]
That codepen demo is cool, but after thinking about it, it's not right to add this functionality to the core plugin. The reason being that we decide on which regions get included not based on countries, but based on their telephone calling codes, so for instance we don't include antarctica as a single entry because it has multiple calling codes... and some countries will have separate entries for their subregions which have different calling codes. So while there will be a lot of overlap, I don't think this is the right data set to build a country dropdown.

**Comment by AnjaneyuluBatta505** [comment]
Hi,
I added  intl-tel-input to my website  it's working fine, but when I click for the first time It is showing a line.
I'm attaching the image here. please help me to solve it.
![screenshot from 2016-04-29 17 12 22](https://cloud.githubusercontent.com/assets/11136503/14934062/6b0bd29e-0ec2-11e6-9032-636ba54a1c28.png)

**Comment by ooctavianus** [comment]
Nice one.
