### ISSUE TITLE
XHR integration with utils.js

### ISSUE THREAD

**Issue by nlwillia** [Bluefieldscom/intl-tel-input#292]
What's your opinion on integrating utils.js via async XHR calls?  The main methods being called seem to be `getExampleNumber` and `formatNumber`.  Deploy libphonenumber on a server behind an interface that satisfies intl-tel-input's needs, and you could avoid the additional ~215KB dependency.  Obviously, this option would require some server-side setup to use, and an async result is going to require some finesse to reconcile with synchronous event input, but the performance might still be reasonable.  Maybe loading utils.js asynchronously is already performant enough on the classes of device you're interested in supporting, and the extra complexity isn't justified, but it seems like it could be done if there were a good enough motivation for it.

**Comment by jackocnr** [comment]
It's a cool idea, but it's beyond the scope of this project. Each person using the plugin would have to setup their own node server, and also the `formatNumber` is called on each keypress, so I don't think it would be fast enough (definitely not on a slow mobile connection).

If you want to try setting this up yourself and adapting the plugin to handle that, and you had good results, and did some kind of blog post about it, I would be happy to link to that!

**Comment by nlwillia** [comment]
Fair enough.  zxcvbn has a similar situation, and seems to work well enough with an async download.  I experimented with an async facade for a remote utils.js and was able to get fair results locally, but the debouncing needed was ugly, and without support from the internals, a bolt-on ends up being hackish and fragile.  At first encounter, the utils download was a bit of size-shock, but you've done a good job of providing the async loading option.
