### ISSUE TITLE
Add the last countries

### ISSUE THREAD

**Issue by jackocnr** [Bluefieldscom/intl-tel-input#297]
Ok I've decided on the criteria for which countries/regions to include in the plugin:
- They must have an [iso2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
- They must have a [country calling code](https://en.wikipedia.org/wiki/List_of_country_calling_codes)
- They must have a flag
- They must be supported by [libphonenumber](https://github.com/googlei18n/libphonenumber)

You can see a list of unsupported countries near the top of [data.js](https://github.com/Bluefieldscom/intl-tel-input/blob/master/src/js/data.js). By this criteria, I think we should add the following:
- Åland Islands (ax)
- Cocos (Keeling) Islands (cc)
- Christmas Island (cx)
- South Georgia and the South Sandwich Islands (gs)
- Pitcairn (pn)
- Svalbard and Jan Mayen (sj)

I have checked and we already have flags for all of them, we just need to add entries for them in data.js.

**Comment by fishman1986** [comment]
I check the libphonenumber, seems it does not support 
# South Georgia and the South Sandwich Islands (gs)
# Pitcairn (pn)
Ignore them?

**Comment by jackocnr** [comment]
Confirmed. Yes ignore them for now (I will update the country support criteria in my original post).

If you have time, could you please open an issue with libphonenumber about adding support for these countries, and link to it here?

**Comment by fishman1986** [comment]
OK, I'm a little busy these days, will do this in recent days

**Comment by fishman1986** [comment]
Hi boss,

According to https://github.com/googlei18n/libphonenumber/issues/76
>Pitcairn has the same issue - that has a comment in the metadata saying that the 30 inhabitants use satellite phones.

>Things like **GS**, HM, UM, TF and EH we will add if we ever have any phone number information about these regions.

I think, let's just keep it in the comments...

**Comment by fishman1986** [comment]
A little question, Åland Islands (ax), obviously, 'Å' is not 'A', I tried to compare 'Å' with 'Z', 'Å' is bigger, so I think I should put it at the tail of the countries list, shouldn't I?

If yes, there is a test case about keyboard shortcuts need to be changed, which assumed that Zimbabwe is the last item.

**Comment by jackocnr** [comment]
Yes if you google "Swedish alphabet order" it looks like it comes after Z, so I agree we should put it at the end. Thanks for this.
