### ISSUE TITLE
Suggestion: Add "ipinfoToken" property in README and script defaults.

### ISSUE THREAD

**Issue by RainierMallol** [Bluefieldscom/intl-tel-input#298]
Hi, thanks for such an amazing utility. I upgraded to the latest version of intl-tel-input, and even though the ipinfoToken property still works, it is nowhere showcased in the code, or in the README. I didn't loose a lot of time with the issue, but I think newcomers would. It would be great if it could be added to both the defaults, and the README.

**Comment by jackocnr** [comment]
That whole system has now been refactored (ipinfoToken has actually been removed). You now do everything yourself using the option geoIpLookup - see the readme.
