### ISSUE TITLE
Can you use the same Flags Image file 

### ISSUE THREAD

**Issue by oliveiraped** [Bluefieldscom/intl-tel-input#299]
Can you use the same Flags Image file has the 

https://github.com/mrmarkfrench/country-select-js

**Comment by jackocnr** [comment]
It seems that plugin is based on this one, and they are using our old flag icons. While it would be possible to use those ones (you'd have to manually update the CSS background-position for every flag!), I would recommend instead getting them to update to the new flags we use here, which look great on retina screens!
