### ISSUE TITLE
How to get the right value from an input on load

### ISSUE THREAD

**Issue by konstrui** [Bluefieldscom/intl-tel-input#304]
If I want to get the value from an input and use the 'getNumber' method, it always returns "".

    $("#rh1TelefoonNummer").intlTelInput("getNumber")

This only works if the page is loaded and I execute this from the Console, not when executing this from the Document Ready.

What am I forgetting?

**Comment by jackocnr** [comment]
getNumber requires loading the utilsScript, so if that hasn't finished, then it wont work. You have to wait for the `done` callback - see readme.
