### ISSUE TITLE
Enter key prevented

### ISSUE THREAD

**Issue by nlwillia** [Bluefieldscom/intl-tel-input#306]
If using this widget in a form, typing a number and hitting enter currently doesn't submit the form because the event is prevented.  I understand not wanting selection of a country from the dropdown to trigger submission, but it's unexpected that the main field would suppress the default behavior.  A user hitting enter when the text part of the field has focus is going to expect it to submit the form like an ordinary text box would.
````
// prevent form from being submitted if "ENTER" was pressed
e.preventDefault();
````

**Comment by jackocnr** [comment]
I cannot reproduce this - enter works on this demo: http://codepen.io/jackocnr/pen/yehvE

The line you quoted only applies when the selected flag is focused, not the input.

**Comment by nlwillia** [comment]
Sorry, should have isolated it before reporting.  I don't know what was going on...it's working now for me too.
