### ISSUE TITLE
Production environment with ipinfo.io.

### ISSUE THREAD

**Issue by adrianmann** [Bluefieldscom/intl-tel-input#312]
Below is my code to load the IntlTelInput:

``` 
    var load_intlTelInput = function(){
        $("#sms").intlTelInput({
            defaultCountry: "auto"
        });
    };

$(document).ready(load_intlTelInput) 
$(window).bind('page:change', load_intlTelInput)
```

This is working great in development but the JS does not seem to be triggering in production.

**Comment by jackocnr** [comment]
If it works in development, then I can't think why it wouldn't work in production. Sounds like a problem with your setup. Try putting a break point in your `load_intlTelInput` function to see if it actually gets called.

Also please see the readme for the `defaultCountry` option - if you set it to auto, it requires the `geoIpLookup` option as well.

**Comment by adrianmann** [comment]
Okay, we may be having an issue with turbolinks, its a Rails project.

However, I do not have the geoIpLookup included so I will try that and get back with confirmation. Thanks.

**Comment by adrianmann** [comment]
Adding `geoIpLookup` did not fix the issue. This issue is still unresolved and probably is to do with out setup. I added some logging to the function and it is being called. However, I would like to keep this ticket open for another while until I get a resolution on our end.

**Comment by adrianmann** [comment]
Our QA team found the problem.

We were using http://ipinfo.io/, as suggested, with SSL and thats why it didn't wok on production, dev is http and production is https. Solved.

**Comment by adrianmann** [comment]
I am currently trying to override the default https in our method.

**Comment by jackocnr** [comment]
Yer the problem is that you need an account to use HTTPS with ipinfo. Either get an account, or try using another service.

**Comment by adrianmann** [comment]
Is it possible to use HTTP on production? I am currently trying that.

**Comment by adrianmann** [comment]
I don't think it is possible to use HTTP on production without changing `var ipinfoURL` in  the source code which we are not going to do obviously. Still researching an alternative solution.

**Comment by jackocnr** [comment]
This is outside the scope of the plugin, but: if your website is served over HTTP, then it's fine to make other HTTP requests. If your website is served over HTTPS, then all of the requests made by that page must be HTTPS otherwise you will get an error.

**Comment by adrianmann** [comment]
Okay, thanks @jackocnr, that makes sense.
