### ISSUE TITLE
bower.json should contain non-minified js file instead of minified js

### ISSUE THREAD

**Issue by vineshhpatel** [Bluefieldscom/intl-tel-input#314]
The main property of the bower.json is used by automated tools (like https://github.com/taptapship/wiredep#what-can-go-wrong). Right now, the bower.json for includes minified file reference. So I suggest only the non-minified versions be included in the bower.json.

**Comment by jackocnr** [comment]
I don't understand why it makes any difference if you include the minified or the non-minified version?

**Comment by vineshhpatel** [comment]
Hi @jackocnr 
Bower [recommends](https://github.com/bower/bower/issues/393) not to use minified files for your main scripts (leave it up to build tools to minify if desired).

**Comment by jackocnr** [comment]
Thanks for pointing this out. Fixed in v6.4.1.

**Comment by vineshhpatel** [comment]
@jackocnr Awesome :+1:
