### ISSUE TITLE
Safari and Chrome problem

### ISSUE THREAD

**Issue by perrycbrown** [Bluefieldscom/intl-tel-input#315]
The formatted phone field limits user to typing only 2 characters in phone field. This is a problem in Safari and Chrome, but not Firefox.

![screen shot 2015-10-29 at 2 31 03 pm](https://cloud.githubusercontent.com/assets/3799732/10829742/dc4cdec6-7e49-11e5-94cf-d09bc307a924.png)

**Comment by jackocnr** [comment]
Hi there, are you seeing any JavaScript errors? What version of the plugin are you using? What initialization options are you using? The [demo page](http://jackocnr.com/intl-tel-input.html) seems to be working fine for me on Chrome.

**Comment by perrycbrown** [comment]
Never mind. It was an unintentional degradation of one of the js files. fixed now.

On Oct 30, 2015, at 12:03 PM, jackocnr <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there, are you seeing any JavaScript errors? What version of the plugin are you using? What initialization options are you using? The demo page<http://jackocnr.com/intl-tel-input.html> seems to be working fine for me on Chrome.

—
Reply to this email directly or view it on GitHub<https://github.com/Bluefieldscom/intl-tel-input/issues/315#issuecomment-152587580>.


Perry Brown

Lead Programmer




THE BIBLE-TEACHING MINISTRY OF ALISTAIR BEGG
pbrown@truthforlife.org<mailto:pbrown@truthforlife.org>
www.truthforlife.org
PO Box 398000 Cleveland, OH 44139
Main: 888.588.7884 / Fax: 440.543.0522
