### ISSUE TITLE
Problem with dynamic creation of input fields

### ISSUE THREAD

**Issue by slavafomin** [Bluefieldscom/intl-tel-input#319]
Hello there!

Thank you for this great plugin!

However, I have an issue with it. If I create input field dynamically and then apply plugin to it, it's content is not properly formatted. I've created a Plunk to demonstrate the problem: http://plnkr.co/edit/nC54UAnan7DYndWAPyrC?p=preview

Could you elaborate please?

Thank you!

**Comment by caseyjhol** [comment]
It's because the number you're using for the dynamic fields is `+71231234567`, which is an invalid phone number. If the number is invalid, it can't be formatted properly. If you use `+79051234567` as the number and add the inputs, it works fine.

**Comment by jackocnr** [comment]
Confirmed. Thank you @caseyjhol
