### ISSUE TITLE
Why not use famfamfam flags?

### ISSUE THREAD

**Issue by omguhh** [Bluefieldscom/intl-tel-input#323]
They look better, and all the flags are the same size so its consistent, ex: the Swiss flag and the Vatican city flag look like squares, very different from the other flags listed.

The sprites [here](http://tkrotoff.github.io/famfamfam_flags/) look much better.  :octocat:

**Comment by jackocnr** [comment]
We used to use them, but unfortunately they didn't provide retina support, so we switched to something else.
