### ISSUE TITLE
change event for changing country

### ISSUE THREAD

**Issue by andriijas** [Bluefieldscom/intl-tel-input#34]
would be nice if there was  a change event triggered when country is changed in the dropdown

**Comment by seaBubble** [comment]
I am still experiencing issues with this, the event is fired but the model is not updated if I first enter the number and then change the flag. If I update the number after changing the flag, the model then picks up the flag. Any ideas?

Thanks,

**Comment by jackocnr** [comment]
@seaBubble please can you describe an example with steps to reproduce?

**Comment by seaBubble** [comment]
Thanks @jackocnr. I am using a directive as follows:

internationalPhoneProvider.set({preferredCountries: ['gb']});

// Set initial country if passed as attribute
scope.$watch(function () {
    return attr.initialCountry;
}, function (newVal) {
    if (angular.isDefined(newVal) && newVal != null && newVal !== '') {
    var country = newVal.toLowerCase();
    internationalPhoneProvider.set({initialCountry: country});
    internationalPhoneProvider.init(elm);
}
});

if (attr.setInitialCountry === undefined || !attr.setInitialCountry) {
    internationalPhoneProvider.init(elm);
}

// Set Selected Country Data
function setSelectedCountryData(model) {
    var getter = $parse(model);
    var setter = getter.assign;
    setter(scope, elm.intlTelInput('getSelectedCountryData'));
}

 // Force input validation if country selection changes but number stays the same
angular.element($window).on('countrychange', function() {
    ctrl.$validate();
    $timeout(function() {
       scope.$apply();
     });
});

// Handle Country Changes.
function handleCountryChange() {
    setSelectedCountryData(attr.selectedCountry);
}

// Country Change cleanup.
function cleanUp() {
    angular.element($window).off('countrychange', handleCountryChange);
}

 // Selected Country Data.
 if (attr.selectedCountry) {
    setSelectedCountryData(attr.selectedCountry);
    angular.element($window).on('countrychange', handleCountryChange);
    scope.$on('$destroy', cleanUp);
}

// Validation.
ctrl.$validators.tInternationalPhone = function (value) {
    // if phone number is deleted / empty do not run phone number validation
   if (value || elm[0].value.length > 0) {
         return elm.intlTelInput('isValidNumber');
   } else {
       return true;
   }
};

// Set model value to valid, formatted version.
ctrl.$parsers.push(function (value) {
    return elm.intlTelInput('getNumber');
});

// Set input value to model value and trigger evaluation.
ctrl.$formatters.push(function (value) {
    if (value) {
        if(value.charAt(0) !== '+') {
            value = '+' + value;
        }
        elm.intlTelInput('setNumber', value);
    }
    return value;
});

Initialising the directive:
<input type="tel" id="mobile" name="mobile" autocomplete="off" placeholder="Mobile Number" data-ng-model="user.mobile" required="required" t-international-phone class="form-control bottom-border-input" data-initial-country="{{defaultCountryCode}}" data-set-initial-country="true">

Now, if I enter a number in the input field (478111111) with UK country code selected, and then change the flag selector to Australia, the model is not updated with the Australian country code, it stays as +44478111111.

Thank you!

**Comment by jackocnr** [comment]
I'm sorry but questions about Angular are outside the scope of this plugin. If you can reproduce your problem without Angular then I'd be happy to look into it for you.

**Comment by MalharDevasthali** [comment]
> There is already a change event triggered on the input element. You can see it in action in this example: http://jackocnr.com/lib/intl-tel-input/examples/gen/country-sync.html
> 
> Is that what you meant?

this link is not working , I am facing same issue , when I enter number first and then change the country then its not working , can you please help how I can get call back when country is getting changed
