### ISSUE TITLE
separateDialCode option

### ISSUE THREAD

**Issue by jackocnr** [Bluefieldscom/intl-tel-input#57]
This has been requested a couple of times, so I thought I'd open it up to debate.

If enabled, what would this change?
- When you select a flag, it will no longer insert the dial code in the input (or try to replace the dial code of any entered number), but instead insert the dial code into the selected-flag div. This will also happen during plugin initialisation (handling any existing input value, or a defaultCountry option), and also if the public method selectCountry is called. That said, when you select a diff flag, we will need to re-format any entered number.
- We will need some nice default styling for the separate dial code area.
- We will force the autoHideDialCode option to false, as this will no longer be relevant. Also this option would obviously be incompatible with the nationalMode option.
- The user will no longer be able to change the country/dial code just by typing in the input (see potential issue/solution below).
- We will need a public getNumber method, which returns the full number (inc. the dial code).
- Formatting/validation will have to be updated to use that getNumber method.

Potential issues:
- Devs may not realise they need to use the getNumber method instead of just using the input value, but maybe we just need to document this clearly...
- Users might be more likely to enter their national telephone numbers if there's no dial code right there in the box. E.g. in the UK, national numbers have an extra "0" at the beginning: "07733 123456", compared to international numbers: "+44 7733 123456", but perhaps this is just a case of getting the design right, so it looks like the dial code is part of the same string...
- Power users may be annoyed that you cant just type the whole number (inc. the dial code) - you have to faff around with clicking the dropdown. OR perhaps if they do type a dial code, that will automatically update the selected one?

Also worth noting that Google and Stripe don't do this on their web forms, but Skype do. To see Google's version, sign out of Gmail, and head to http://gmail.com and click signup. To see Stripe's version, go to https://stripe.com/docs/tutorials/checkout and hit "Pay with card" and then "Remember me". To see Skype's version, go to https://login.skype.com/account/signup-form.

**Comment by mkpasala** [comment]
Please post an example of it on stackbliz.com for angular 4. @jackocnr
