### ISSUE TITLE
Static formatNumber method

### ISSUE THREAD

**Issue by jackocnr** [Bluefieldscom/intl-tel-input#59]
Expose the formatting functionality in a static function, so devs can display formatted numbers on the page without putting them in an input and initialising the plugin. This would take 1 argument: the number, and would extract it's dial code, and use that to fetch the formatting information.

We already have 2 static methods: getCountryData and setCountryData (at the bottom of intlTelInput.js) so we can copy the style of those to create new ones. Only problem I foresee is accessing private instance methods that we will need to use, like _getDialCode and _getCountryData. Perhaps these could be updated to be static methods as well.

**Comment by jamauro** [comment]
I would love to see this. Basically, I want to take the international format that I have stored (e.g. "+15125555555") and pretty format it for display (e.g. "(512) 555-5555). Does this ability already exist and I've just missed it?

**Comment by jackocnr** [comment]
Hmm you can do this once you have [utils.js](https://github.com/Bluefieldscom/intl-tel-input/wiki/utils.js) loaded on the page. Something like `intlTelInputUtils.formatNumberByType("+15125555555", null, 2);`. 

The problem is that the way we load utils.js is through an instance of the plugin, so if you're not using the plugin on that page you would need to load it manually. (be careful as it's a pretty heavy file - see the sourcecode of the plugin to see how we lazy load it after the window.load event has fired to make sure it doesn't block).

One potential solution to this problem would be to create a static method on the plugin to safely load utils.js. So you could do something like `$.fn.intlTelInput.loadUtils();`. What do you think?

**Comment by jackocnr** [comment]
FYI `loadUtils` is a static method as of v7.0.0
