### ISSUE TITLE
Retina flag icons

### ISSUE THREAD

**Issue by jackocnr** [Bluefieldscom/intl-tel-input#65]
The current flag icons look pretty bad on my new retina macbook.

**Comment by rileyjshaw** [comment]
+1 on https://github.com/lipis/flag-icon-css, seems like a great direction to move towards

**Comment by jackocnr** [comment]
Very interesting, thanks guys. I probably wont have time to implement this in the near future, but I'm very open to pull requests! My email is on my website (in my Github profile) if you have any questions at all.

**Comment by khanhvuNOIS** [comment]
Looking forward about this feature

**Comment by patw0929** [comment]
I replaced original flag icons with SVG flag icons from https://github.com/lipis/flag-icon-css in my fork:
https://github.com/patw0929/intl-tel-input/tree/retina-flag-icons

Some of flag icons seem like a little blurry on my laptop, but look good on my smart phone. 
Need find other way to refine it.

**Comment by jackocnr** [comment]
Wow this is amazing - thanks for doing this! How did you generate all the background position percentages? And how did you generate the png fallback version?

My main concern with this approach is that the resulting SVG is over 3MB, as opposed to the original PNG which was just 70KB. But I see you've already generated that fallback PNG version - what if we just generate a decent retina PNG version that looks good on retina screens, but keeps the filesize low? Currently the flags are 11px tall - would it be possible to generate a version at 22px tall?

**Comment by patw0929** [comment]
Thank you for your advice! I regenerated the @2x version PNG of flags in this branch: https://github.com/patw0929/intl-tel-input/tree/retina-%402x-flag-icons
(Due to the ratio of https://github.com/lipis/flag-icon-css is 4x3, so I revised the size in 16px*12px.)

I used `grunt-svg-sprite`, `grunt-svg2png` and `grunt-retinafy` to generate these files.

--
Please give me some advice again.
Thank you :)

**Comment by jackocnr** [comment]
Great! Ok so more feedback: firstly, some flags have white backgrounds and no borders (like Japan), which looks bad, so let's add this CSS rule: `.iti-flag {outline: 1px solid #DFDFDF;}`. Secondly, at the new resolution of 16x12, the US flag looks terrible on non-retina devices, and looking at the [flag icon demo website](http://lipis.github.io/flag-icon-css/), they always use odd numbers for the height in the examples, and I've tried a few different things with the US flag and 18x13 looks best, so can we try that? Thanks for contributing!

**Comment by patw0929** [comment]
Thanks for feedback! I have done these fix in same branch:

1. Add outline
2. Change non-retina icon resolution to 18x13
3. Generate 50% scaled PNG from 50% scaled SVG

Point 3 is the test for which way is better. It seems like original way is better in my opinion.
If you need to compare them, you can revert the last commit `b1dfcbb842666f31c4b285014795ce21e636ebec`.

Thank you!

**Comment by jackocnr** [comment]
Great work. I agree that the original way is better. If you want to revert to that and then do a pull request, then I will merge it in!

Thanks again.

**Comment by girtsl** [comment]
Is it just me or the flags from https://github.com/lipis/flag-icon-css are not quite right?
For example, the shade of yellow is noticeably darker than in [Swedish flag](http://en.wikipedia.org/wiki/Sweden#mediaviewer/File:Flag_of_Sweden.svg).
I don't have a retina display if that matters. The old icons looked much crisper and better.

**Comment by jackocnr** [comment]
Yer I think the old icons were probably better for non-retina screens, but they looked really bad on retina screens (which are becoming way more popular). The new icons look great on retina screens and the new system is SO much better for us in terms of implementation (we can pull in changes and re-build the sprite/CSS automatically - as opposed to the old system where we had to re-build everything manually every time).

If you have feedback on the icons, please raise an issue on their Github project.

**Comment by girtsl** [comment]
I guess it all boils down to your target audience. If it's mostly Apple devices with Retina displays, then, without doubt, the new icons look better and yes, those displays are becoming way more popular. Of course, the ease of use matters too.
On the other hand, last time I checked, PCs (which usually don't have Retina displays) are still way more popular in the consumer audience.

**Comment by jackocnr** [comment]
I'm afraid the new flag solution is just so much better from an implementation/maintenance perspective, and the flags are good enough on non-retina devices (they do the job), that this is not going to change. (unless you find another source of retina flag icons we could use).

Looks like that guy is actively maintaining that project, which is good news. And this is open source, so feel free to jump in and fix things yourself!

**Comment by girtsl** [comment]
I meant no offense with my comment, I'm grateful for the work you guys and the whole open source community does! I completely understand your need for easily obtainable source of icons.
However, I personally would not deliver/integrate a product whose quality is seriously lacking. IMHO flag images is a more serious topic than e.g. file type icons as having an incorrect country flag might insult the patriots of that country and form a negative impression of the site as a whole. Again, this is not about retina or non-retina resolution but the quality/correctness of flag icons. I can only hope you guys thoroughly evaluated all available options before committing to this project. In most applications correctness is above eye candy.
Thanks for doing a great job!

**Comment by jackocnr** [comment]
Ok I've looked through all of the open issues on the flag-icon-css project, and for the countries we support, there is one flag that is wrong (the US Virgin Islands flag is currently the British Virgin Islands flag), and three that have a small issue e.g. positioning/size of elements (Sri Lanka, Niue and India).

I'm sure we can fix these issues in no time! Have you ever worked with SVGs before? AFAIK it's just like HTML. If you look at a simple flag like France (click [here](https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/fr.svg) to see the flag, then click "raw" to view the SVG code), you can see that it's not very complicated. Maybe you could look into fixing those 4 flags and then problem solved!

**Comment by girtsl** [comment]
I'm afraid it's not just the open issues. For example, the Swedish flag not only had wrong colors but proportions of the flag's elements. This and other issue(s) might originate from the original author's decision to use 4:3 format for all flags (why?). 

Apart from the fact that both SVG are HTML are markup languages with XML-like syntax, they don't have much in common. Sure, color fixes (https://github.com/lipis/flag-icon-css/issues/45) and simple shapes like rectangles could be easy to fix, but I imagine more complex shapes would require someone with deeper SVG knowledge.

Unfortunately I already have too many commitments to actively participate in fixing those SVGs. Even more so, once I realized that the flag elements' proportions are wrong, one would first need to go trough all flag images and compare them to the official flags to identify everything that needs fixing. As the current maintainer points out in comments, he doesn't have much time to spend either.

**Comment by patw0929** [comment]
Thanks for feedback & discussion!
I made another branch to refine it: https://github.com/patw0929/intl-tel-input/tree/replace-flag-icons-with-stevenrskelton-flag-icon

In this branch, I replaced the icons with [flag-icon](https://github.com/stevenrskelton/flag-icon)'s icons. It provides retina & non-retina icons (seems it's old flag icons) at the same time. 

Just another test. :) I'm not sure which way is better.

**Comment by jackocnr** [comment]
Thanks Patrick!

Some quick thoughts on using the flag-icon project:
- It's great that it includes the different set of low-res flags which are optimised for non-retina screens, BUT is it worth the extra CSS weight? It means that every user (retina and non-retina) will need to download the CSS rules for both flag sprites (each sprite has aprx 250 `background-position` rules) - this has doubled the filesize of the build CSS file from 20KB to 40KB. (IMO this is not worth it - I think the scaled down retina icons look fine on non-retina screens)
- Slower maintenance: having 2 sets of flag icons means any change to a flag (bug fix or flag change or new country etc) needs to be done twice, and in 2 different systems. Realistically, it probably means contacting the 2 original artists who created the icon sets in the first place, and asking them both to make the change...
- Their version of the US Virgin Islands flag is the correct one, as opposed to the flag-icon-css project which has the wrong one.
- They have those same small issues with the Sri Lanka, Niue and India flags (which is weird because those issues are not present on that Wikimedia Commons link you posted - I guess it's to do with forcing the 4x3 or 1x1 ratio).

Patrick - do we need to have consistent dimensions of the flags for our automatic sprite/CSS generation to work? Or theoretically, if we found a project that just hosted all of the Wikimedia Commons flags with all different ratios, could we make that work? We could export the SVGs at a consistent width, but with varying heights? They would need to have consistent widths to look good as a list in the dropdown. I'm just thinking out loud here...

**Comment by patw0929** [comment]
Hi Jack, I found another project named [region-flags](https://github.com/behdad/region-flags). According to the project's introduction, their flag icons were downloaded from Wikipedia.

I made the repo as a submodule in my another test branch (https://github.com/patw0929/intl-tel-input/tree/replace-flags-with-svg-from-wikipedia), and revising the grunt task & rebuilding the flag icons/CSS again. Because some of the flags might be higher than the `.selected-flag` block, so I set the maxWidth & maxHeight in the exporting task.

Known issue:
* Some flags should be optimized, like the position/background color of Nepal flag in the dropdown list

**Comment by jackocnr** [comment]
Hi Patrick, thanks again - great work!

Thoughts:
- Don't worry about the country name alignment in the dropdown list - I can fix that.
- This flag project seems perfect - it has an update script which literally pulls everything down from Wikimedia Commons!
- The flags are too small in this build - US and GB look bad (GB is actually missing one of the red stripes because it's so low res). I tried changing the maxWidth and maxHeight in svg_sprite.js and re-built, but it didn't work for some reason. Shall we try 18x13 again? We may need to go bigger...
- The new sprites have a massive filesize e.g. flags@2x.png has grown from 151KB to 344KB! I see you're using a new diagonal layout - can we not use the old layout anymore?

I'm also unable to test on a non-retina screen right now, so will do that this afternoon.

**Comment by patw0929** [comment]
Sorry for the late reply. Getting a little busy at work these days.

Same branch: https://github.com/patw0929/intl-tel-input/tree/replace-flags-with-svg-from-wikipedia

I have revised the issues you mentioned above.

* Replace grunt-svg-sprite with grunt-spritesmith to build flag icons.
* Build PNG sprite from region-flags's png version. (But seems we need to resize them smaller in grunt task first)
* Revise resolution to 18x13 again.
* Use packed layout.

Thanks!

**Comment by jackocnr** [comment]
That's great thank you. If you want to submit a pull request, then I will do some tweaks over the top.

For my notes:
- I've decided on a size of 20x15 (ironically this 4x3 ratio gets the most consistent results), but this requires some other tweaks to the CSS (selected-flag width and arrow left position)
- Selected flag vertical centering: use margin:auto, top:0, bottom:0
- Thin flag alignment in dropdown: use a wrapper div with display:inline-block, width:20, margin-right:6 and make sure no spaces between elements in markup!
- If artifacts on Chrome on retina device, use padding when building sprite and find/file bug report with Blink

**Comment by jackocnr** [comment]
Done. v5.6.0. Feedback welcome.

I had to add 2px padding to the sprite as I was seeing flags leaking into each other on Chrome on my retina macbook (but not in Safari or Firefox). I can't find an issue for this, so I may post one when I get a chance.

@patw0929 one optimisation we could make: we currently have 251 countries each with this same line of CSS: `width: retina-size(40px);` - would it be possible to pull that out and apply it to the common `.iti-flag` selector, and then add an override for the ~5 countries that have a smaller width?

**Comment by patw0929** [comment]
@jackocnr
OK, as you mentioned above, I made some modified at https://github.com/patw0929/intl-tel-input/tree/refine-scss
Please give me some feedback. Thanks!

**Comment by jackocnr** [comment]
Yer that look's great thanks - can you do a pull request?

**Comment by girtsl** [comment]
Thank you, the new icons look much better than the previous ones! 
The box-shadow rule of .iti-flag class still makes them appear slightly blurry, but I understand this is for flags that have white background.

**Comment by jackocnr** [comment]
@patw0929 unfortunately there is a problem with flag alignment on non-retina screens: https://github.com/Bluefieldscom/intl-tel-input/issues/178

**Comment by avimar** [comment]
The regular flags are rather dull -- both when seem by itself and inside the input. It's rather just _blurry_ compared to gosquared's flags. I looked at the retina sample you set up... but yikes, 500kb!

Here's a sample comparing 2 flags in 2 styles: http://codepen.io/anon/pen/LkBGyb

I can see why you are using behdad/region-flags -- it seems rather official and kept up to date.
They have full SVGs and rather nice looking pngs... I have no clue how the sprite generation works, is there a way for it to be sharper?
Or to have a medium sized file that's between the 68kb and 500kb flags image? Since you are supporting IE8, apparently svg-sprites aren't available...

I looked around a bit, there's https://www.flag-sprites.com/ can generate a 150kg sprite + 12kb unminified CSS of 32x32 flag size, using gosquared: see [image](https://www.flag-sprites.com/gen/flags.png?set=gosquared-large&countries=ad,ae,af,ag,ai,al,am,an,ao,ar,as,at,au,aw,az,ba,bb,bd,be,bf,bg,bh,bi,bj,bm,bn,bo,br,bs,bt,bw,by,bz,ca,cd,cf,cg,ch,ci,ck,cl,cm,cn,co,cr,cu,cv,cy,cz,de,dj,dk,dm,do,dz,ec,ee,eg,eh,er,es,et,fi,fj,fm,fo,fr,ga,gb,gd,ge,gg,gh,gi,gl,gm,gn,gp,gq,gr,gt,gu,gw,gy,hk,hn,hr,ht,hu,id,ie,il,im,in,iq,ir,is,it,je,jm,jo,jp,ke,kg,kh,ki,km,kn,kp,kr,kw,ky,kz,la,lb,lc,li,lk,lr,ls,lt,lu,lv,ly,ma,mc,md,me,mg,mh,mk,ml,mm,mn,mo,mq,mr,ms,mt,mu,mv,mw,mx,my,mz,na,nc,ne,ng,ni,nl,no,np,nr,nz,om,pa,pe,pf,pg,ph,pk,pl,pr,ps,pt,pw,py,qa,re,ro,rs,ru,rw,sa,sb,sc,sd,se,sg,si,sk,sl,sm,sn,so,sr,st,sv,sy,sz,tc,td,tg,th,tj,tl,tm,tn,to,tr,tt,tv,tw,tz,ua,ug,us,uy,uz,va,vc,ve,vg,vi,vn,vu,ws,ye,za,zm,zw).
.. but I don't know how up to date or not they are. Also, I don't know how to resize them but that's a CSS issue.

In the mean time, I think I'll just leave what I have -- loading 4-5 png's for select countries is OK for now...

Thanks for all your hard work!

**Comment by avimar** [comment]
Hmm. The retina @2x looks much more decent... and the included one is only 150kb already!
But when I just update the path for default, all the flags are off. How do I for everyone to use the retina image? Or just, make it work on my 1080p screen?

Thanks!

**Comment by jackocnr** [comment]
@avimar as I said in [this comment](https://github.com/jackocnr/intl-tel-input/issues/457#issuecomment-235979021) you need to override the `background-image` AND `background-size` CSS rules to always be the retina versions.

**Comment by avimar** [comment]
Hmm. I tried overriding both the `background-size:11260px 30px;` and `background-image:url("../img/flags@2x.png");` but that doesn't produce any aligned flags on chrome desktop (just some cool shaped blobs of color!).
From the huge flags version you made, you have all updated positions:
e.g. `.iti-flag.za{height:14px;background-position:-5566px 0px}` vs `.iti-flag.za{height:54px;background-position:-20731px 0px}`

If I want to force retina, do I need to do the same thing and rebuild the assets & entire css?

**Comment by jackocnr** [comment]
@avimar the retina background-position rule is `background-size: 5630px 15px;`. You can see it working here: http://codepen.io/jackocnr/pen/mEjzgY

**Comment by avimar** [comment]
Oh, that works! Thanks.
I can on my "normal" 1080p screen a _slight_ increase in quality.
I suppose a link to that codepen will help others like myself...

Hmm, somehow in my site, it loads both the flag.png and the flag@2x.png files even when I put it in the <style> tag instead of externally loaded. Weird, that's not a problem on codepen.

I think I'm gonna stick with the shiny gosquared icons, they look pretty sweet. Oh well, at least I _chose_ an additional dependency.
