### ISSUE TITLE
After formatting is applied, lose width and control styles from Bootstrap 3

### ISSUE THREAD

**Issue by kwhinnery** [Bluefieldscom/intl-tel-input#72]
I am using the plugin with the latest version of Bootstrap, and when the formatting is applied by this plugin, the sizing behavior provided by the `form-control` class no longer applies. Further, I can't apply a 100% width or a block display setting to the input field.

Before `$('#elem').intlTelInput()`:

![](http://demo.kevinwhinnery.com/upload/Click_To_Call_Tutorial-20140822-135447.png)

After `$('#elem').intlTelInput()`:

![](http://demo.kevinwhinnery.com/upload/Click_To_Call_Tutorial-20140822-135621.png)

Markup:

``` html
<div class="row">
  <div class="col-md-12">
    <form role="form" action="/call" method="POST">
      <div class="form-group">
        <h3>Call Sales</h3>
        <p class="help-block">Are you interested ... sales department.</p>
      </div>
      <div class="form-group">
        <input type="text" id="phoneNumber" placeholder="(651) 555-7889" 
          class="form-control">
      </div>
      <button type="submit" class="btn btn-default">Contact Sales</button>
    </form>
  </div>
</div>
```

JS:

``` javascript
$(function() {
    $('#phoneNumber').intlTelInput({
        responsiveDropdown: true,
        autoFormat: true,
        utilsScript: '/vendor/intl-phone/libphonenumber/build/utils.js'
    });
});
```

Other than this it's working fantastically.  Thanks for contributing!

**Comment by Sktbanerjee1** [comment]
Hi, I am facing the same issue. Tried the above-mentioned fix, but so far no luck. Any help would be great.

**Comment by nickona** [comment]
This worked for me:

`.iti.iti--allow-dropdown {
    width: 100%
}`
