### ISSUE TITLE
input maxlength attribute

### ISSUE THREAD

**Issue by marapupa** [Bluefieldscom/intl-tel-input#78]
How to limit length of input content?
maxlength attr doesn't work.

**Comment by gizmo49** [comment]
for anyone else still trying this I solved it this way `document.querySelector("input[type='tel']").setAttribute("maxlength", "10");`

**Comment by jackocnr** [comment]
I have now added a `strictMode` option, which prevents users from entering invalid characters and caps the input at the maximum valid number length. Added in v20.2.0.
