### ISSUE TITLE
Limit Input Characters to Formatted String Length

### ISSUE THREAD

**Issue by tadarice** [Bluefieldscom/intl-tel-input#79]
It would be nice if the plugin would not allow users to input characters beyond the length of the auto formatted string.

Thanks.

**Comment by rob101** [comment]
Is this a setting I need to set? I don't see this functionality in the current version.

**Comment by jackocnr** [comment]
This became an option (`preventInvalidNumbers`), which I ultimately removed this in v5.0.0.

"Removed preventInvalidNumbers as was wrongly using libphonenumber's AsYouTypeFormatter, which was broken and they explicitly said shouldn't be used for that"

**Comment by iamstarkov** [comment]
so is there a way to limit the number once it become over autoformat string?

**Comment by iamstarkov** [comment]
this should work

```js
$('#form').find('input#phone').on('keyup', function(event) {
  var phone = $('#phone').intlTelInput("getNumber");
  var error = $('#phone').intlTelInput("getValidationError");
  var TOO_LONG = intlTelInputUtils.validationError.TOO_LONG;
  if (error === TOO_LONG) {
    event.preventDefault();
  }
};);
```

**Comment by iamstarkov** [comment]
but apparently it doesnt. the problem is that `intlTelInputUtils.getValidationError("+467000012345")`  still `IS_POSSIBLE`, but breaks the autoformat

**Comment by iamstarkov** [comment]
@jackocnr what do you think?

**Comment by iamstarkov** [comment]
nah, its working.

**Comment by jackocnr** [comment]
No there is not currently a way to limit the number once it goes over the autoformat length.

Your code would not work because it would prevent entering the first digits of a number. One way to do it would be to check if the validation error returned is "TOO_LONG" but this is currently broken for US numbers - see above.

Also a lot of UX guides advise against this kind of prohibitive functionality.

**Comment by eudisd** [comment]
So what is the status of this @jackocnr will this be fixed or are there plans to fix?

**Comment by jackocnr** [comment]
No plans to add this functionality as IMO it is bad practice, not to mention the fact that there is no reliable way to do it (libphonenumber do not provide this functionality).

**Comment by Tofandel** [comment]
Couldn't we just prevent letters in the input with an option at least?

**Comment by mguinness** [comment]
> Couldn't we just prevent letters in the input with an option at least?

I'm new to this library, but could you use the [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) attribute?
