### ISSUE TITLE
utilsScript loading and autoFormat doesn't work if intlTelInput is loaded after window.load

### ISSUE THREAD

**Issue by ur001** [Bluefieldscom/intl-tel-input#85]
I have popups loaded via $.ajax. They contain html/styles/scripts. 
For example, phone confirmation dialog:

``` html
<input type="tel"/>

<script src="/static/js/intlTelInput.min.js"></script>
<link rel="stylesheet" href="/static/intl-tel-input/css/intlTelInput.css"/>

<script>
    $(function(){
        $('[type=tel]').intlTelInput(...);
    });
</script>
```

intlTelInput don't loads utilsScript, because it loaded after window.load and has code:

``` javascript
    windowLoaded = false;

    $(window).load(function() {
        windowLoaded = true;
    });

    ...

    if (windowLoaded) {
        injectUtilsScript();
    } else {
        $(window).load(injectUtilsScript);
    }
```

**Comment by ManishJha424** [comment]
in JS File
$.fn[pluginName].handleUtils = function ()
    {
        $(".intl-tel-input input").intlTelInput("handleUtils");
    }
In Html
 $("#phoneNumber").keyup(function (event) {
                $.fn.intlTelInput.handleUtils();
            });

it will load Automatically Utils.js and autoformat Phone no.
