### ISSUE TITLE
Is there a way to get country information for a given number?

### ISSUE THREAD

**Issue by Senjai** [Bluefieldscom/intl-tel-input#88]
Without initializing the input? I have a toggleable input so the input is not always available. However I would like to display the flag on the static element as well. Is there a way I can ask the library to give me the relevant country data for a specific number?

**Comment by evanjmg** [comment]
Has that f-display branch been merged into master?

**Comment by jackocnr** [comment]
No, I gave up on this when @Senjai stopped replying...

Can you describe your use case in as much detail as possible?
