### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by MB34** [Bluefieldscom/intl-tel-input#93]
Can you add support for extensions for use for Business phone numbers? If you weren't' aware, libphonenumber supports 'ext.' and 'x' for extension prefixes.

**Comment by jackocnr** [comment]
FYI someone sponsored this feature, and so it got built! See the `allowExtensions` option.

**Comment by MB34** [comment]
Have you updated your examples to show this new feature? I didn't see it.

**Comment by jackocnr** [comment]
No I have not. The logic is: if you type a digit beyond the maximum valid length for the selected country, it will add " ext. " and then that digit (and any further ones you may type after that).

I'm open to a pull request to add an example!

**Comment by mcapodacqua** [comment]
@jackocnr Any updates with this? I'd like to see the example working since I'm implementing this plugin in version 5.8.7 and I cannot put extensions in numbers.

Thanks!

**Comment by jackocnr** [comment]
I updated [this codepen](http://codepen.io/jackocnr/pen/yehvE) to set allowExtensions to true. Does that work for you?

**Comment by MB34** [comment]
Looks like you also need to update the placeholder if the option is available.
